-- =========================================================================
-- SCRIPT OFICIAL DE ATUALIZAÇÃO DE CEPS E ENDEREÇOS - REDE SPOLETO
-- Total de Lojas Enriquecidas: 409
-- =========================================================================

UPDATE public.stores SET cep = '58037-000', city = 'João Pessoa', state = 'PB', address = 'Avenida Governador Flávio Ribeiro Coutinho, 115 - Manaíra (MAG SHOPPING)' WHERE id = 'store-1' OR code = 'SPO-001';
UPDATE public.stores SET cep = '58036-853', city = 'João Pessoa', state = 'PB', address = 'Rua Ulrico Oliveira Cavalcanti, 805 - Aeroclube (MANAIRA SHOPPING)' WHERE id = 'store-2' OR code = 'SPO-002';
UPDATE public.stores SET cep = '58055-018', city = 'João Pessoa', state = 'PB', address = 'Avenida Hilton Souto Maior - Mangabeira (MANGABEIRA SHOPPING)' WHERE id = 'store-3' OR code = 'SPO-003';
UPDATE public.stores SET cep = '58408-000', city = 'Campina Grande', state = 'PB', address = 'Avenida Prefeito Severino Cabral, 1050 - Vila Cabral (PARTAGE SHOPPING CAMPINA GRANDE)' WHERE id = 'store-4' OR code = 'SPO-004';
UPDATE public.stores SET cep = '01000-000', city = 'João Pessoa', state = 'PB', address = 'SPOLETO EPITACIO MM - João Pessoa/PB' WHERE id = 'store-5' OR code = 'SPO-005';
UPDATE public.stores SET cep = '51210-902', city = 'Recife', state = 'PE', address = 'Praça Ministro Salgado Filho, s/n - Imbiribeira (Aeroporto Internacional do Recife)' WHERE id = 'store-6' OR code = 'SPO-006';
UPDATE public.stores SET cep = '52060-350', city = 'Recife', state = 'PE', address = 'Rua César Loureiro, 70 - Casa Forte (PLAZA CASA FORTE)' WHERE id = 'store-7' OR code = 'SPO-007';
UPDATE public.stores SET cep = '51020-900', city = 'Recife', state = 'PE', address = 'Rua Padre Carapuceiro, 777 - Boa Viagem (SHOPPING RECIFE)' WHERE id = 'store-8' OR code = 'SPO-008';
UPDATE public.stores SET cep = '51110-160', city = 'Recife', state = 'PE', address = 'Avenida República do Líbano, 251 - Pina (SHOPPING RIOMAR RECIFE)' WHERE id = 'store-9' OR code = 'SPO-009';
UPDATE public.stores SET cep = '50110-900', city = 'Recife', state = 'PE', address = 'Avenida Governador Agamenon Magalhães, 153 - Santo Amaro (SHOPPING TACARUNA)' WHERE id = 'store-10' OR code = 'SPO-010';
UPDATE public.stores SET cep = '58700-070', city = 'Patos', state = 'PB', address = 'Rua Doutor Pedro Firmino - Centro (PATOS SHOPPING)' WHERE id = 'store-11' OR code = 'SPO-011';
UPDATE public.stores SET cep = '01000-000', city = 'Juazeiro', state = 'BA', address = 'SPOLETO JUA GARDEN - Juazeiro/BA' WHERE id = 'store-12' OR code = 'SPO-012';
UPDATE public.stores SET cep = '57100-000', city = 'Maceió', state = 'AL', address = 'Rodovia BR-104, km 91 - Tabuleiro do Pinto (Aeroporto Zumbi dos Palmares)' WHERE id = 'store-13' OR code = 'SPO-013';
UPDATE public.stores SET cep = '01000-000', city = 'Maceió', state = 'AL', address = 'SPOLETO JATIUCA MM - Maceió/AL' WHERE id = 'store-14' OR code = 'SPO-014';
UPDATE public.stores SET cep = '01000-000', city = 'Maceió', state = 'AL', address = 'SPOLETO GRUTA MM - Maceió/AL' WHERE id = 'store-15' OR code = 'SPO-015';
UPDATE public.stores SET cep = '57038-000', city = 'Maceió', state = 'AL', address = 'Avenida Comendador Gustavo Paiva, 5945 - Cruz das Almas (Parque Shopping Maceió)' WHERE id = 'store-16' OR code = 'SPO-016';
UPDATE public.stores SET cep = '42702-400', city = 'São Paulo', state = 'SP', address = 'Rua Maria Isabel dos Santos, s/n - Centro (Parque Shopping Bahia)' WHERE id = 'store-17' OR code = 'SPO-017';
UPDATE public.stores SET cep = '41820-021', city = 'Salvador', state = 'BA', address = 'Avenida Tancredo Neves, 3133 - Caminho das Árvores (Salvador Shopping)' WHERE id = 'store-18' OR code = 'SPO-018';
UPDATE public.stores SET cep = '40140-902', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida Centenário, 2992 - Chame-Chame (Shopping Barra)' WHERE id = 'store-19' OR code = 'SPO-019';
UPDATE public.stores SET cep = '01109-010', city = 'São Paulo', state = 'SP', address = 'Avenida Cruzeiro do Sul, 1100 - Canindé (SHOPPING DA BAHIA)' WHERE id = 'store-20' OR code = 'SPO-020';
UPDATE public.stores SET cep = '01000-000', city = 'Salvador', state = 'BA', address = 'SPOLETO SHOPPING PARALELA - Salvador/BA' WHERE id = 'store-21' OR code = 'SPO-021';
UPDATE public.stores SET cep = '01000-000', city = 'Natal', state = 'RN', address = 'SPOLETO MIDWAY SHOPPING (ficou fechada) - Natal/RN' WHERE id = 'store-22' OR code = 'SPO-022';
UPDATE public.stores SET cep = '17012-900', city = 'Bauru', state = 'SP', address = 'Rua Henrique Savi, 15-55 - Vila Nova Cidade Universitária (BAURU SHOPPING)' WHERE id = 'store-23' OR code = 'SPO-023';
UPDATE public.stores SET cep = '17012-900', city = 'Bauru', state = 'SP', address = 'Rua Henrique Savi, 15-55 - Vila Nova Cidade Universitária (BOULEVARD BAURU SHOPPING)' WHERE id = 'store-24' OR code = 'SPO-024';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO EL DOURADO EVENTOS - São Paulo/SP' WHERE id = 'store-25' OR code = 'SPO-025';
UPDATE public.stores SET cep = '13208-056', city = 'Jundiaí', state = 'SP', address = 'Avenida Nove de Julho, 3333 - Anhangabaú (MAXI SHOPPING JUNDIAI)' WHERE id = 'store-26' OR code = 'SPO-026';
UPDATE public.stores SET cep = '13309-900', city = 'Itu', state = 'SP', address = 'Avenida Doutor Ermelindo Maffei, 1199 - Jardim Paraíso (PLAZA SHOPPING ITU)' WHERE id = 'store-27' OR code = 'SPO-027';
UPDATE public.stores SET cep = '13348-500', city = 'Indaiatuba', state = 'SP', address = 'Alameda Filtros Mann, 670 - Jardim Tropical (POLO SHOPPING INDAIATUBA)' WHERE id = 'store-28' OR code = 'SPO-028';
UPDATE public.stores SET cep = '13840-000', city = 'Mogi Guaçu', state = 'SP', address = 'Rua José Alves, 100 - Centro (BOULEVARD MOGI GUAÇU)' WHERE id = 'store-29' OR code = 'SPO-029';
UPDATE public.stores SET cep = '12215-900', city = 'São José dos Campos', state = 'SP', address = 'Avenida Deputado Benedito Matarazzo, 9403 - Jardim Oswaldo Cruz (CENTER VALE SHOPPING)' WHERE id = 'store-30' OR code = 'SPO-030';
UPDATE public.stores SET cep = '12242-000', city = 'São José dos Campos', state = 'SP', address = 'Avenida São João, 2200 - Jardim das Colinas (SHOPPING COLINAS)' WHERE id = 'store-31' OR code = 'SPO-031';
UPDATE public.stores SET cep = '13565-900', city = 'São Carlos', state = 'SP', address = 'Passeio dos Flamboyants, 200 - Parque Faber Castell (IGUATEMI SAO CARLOS)' WHERE id = 'store-32' OR code = 'SPO-032';
UPDATE public.stores SET cep = '12327-000', city = 'Jacareí', state = 'SP', address = 'Rua Olímpio Catão, 500 - Centro (JACAREI SHOPPING)' WHERE id = 'store-33' OR code = 'SPO-033';
UPDATE public.stores SET cep = '14801-912', city = 'Araraquara', state = 'SP', address = 'Avenida Alberto Benassi, 2270 - Jardim dos Manacás (JARAGUA ARARAQUARA)' WHERE id = 'store-34' OR code = 'SPO-034';
UPDATE public.stores SET cep = '13208-056', city = 'Jundiaí', state = 'SP', address = 'Avenida Nove de Julho, 3333 - Anhangabaú (JUNDIAI SHOPPING)' WHERE id = 'store-35' OR code = 'SPO-035';
UPDATE public.stores SET cep = '01000-000', city = 'Rio Claro', state = 'SP', address = 'SPOLETO SHOPPING RIO CLARO - Rio Claro/SP' WHERE id = 'store-36' OR code = 'SPO-036';
UPDATE public.stores SET cep = '04691-000', city = 'São Paulo', state = 'SP', address = 'Avenida das Nações Unidas, 22540 - Jurubatuba (SHOPPING SP MARKET)' WHERE id = 'store-37' OR code = 'SPO-037';
UPDATE public.stores SET cep = '12030-000', city = 'Taubaté', state = 'SP', address = 'Avenida Charles Schnneider, 1700 - Vila Costa (TAUBATE SHOPPING)' WHERE id = 'store-38' OR code = 'SPO-038';
UPDATE public.stores SET cep = '12230-000', city = 'São José dos Campos', state = 'SP', address = 'Avenida Andrômeda, 227 - Jardim Satélite (VALE SUL SHOPPING)' WHERE id = 'store-39' OR code = 'SPO-039';
UPDATE public.stores SET cep = '01000-000', city = 'Valinhos', state = 'SP', address = 'SPOLETO SHOPPING VALINHOS - Valinhos/SP' WHERE id = 'store-40' OR code = 'SPO-040';
UPDATE public.stores SET cep = '01000-000', city = 'Sorocaba', state = 'SP', address = 'SPOLETO SOROCABA MM - Sorocaba/SP' WHERE id = 'store-41' OR code = 'SPO-041';
UPDATE public.stores SET cep = '07190-100', city = 'Guarulhos', state = 'SP', address = 'Rodovia Hélio Smidt, s/n - Cumbica (Aeroporto Internacional de Guarulhos)' WHERE id = 'store-42' OR code = 'SPO-042';
UPDATE public.stores SET cep = '18048-110', city = 'Sorocaba', state = 'SP', address = 'Avenida Professora Izoraida Marques Peres, 401 - Parque Campolim (SHOPPING IGUATEMI ESPLANADA)' WHERE id = 'store-43' OR code = 'SPO-043';
UPDATE public.stores SET cep = '18078-005', city = 'Sorocaba', state = 'SP', address = 'Avenida Itavuvu, 3373 - Jardim Santa Cecília (SHOPPING CIDADE SOROCABA)' WHERE id = 'store-44' OR code = 'SPO-044';
UPDATE public.stores SET cep = '12091-000', city = 'Taubaté', state = 'SP', address = 'Avenida Dom Pedro I, 7181 - Jardim Baronesa (VIA VALE GARDEN SHOPPING)' WHERE id = 'store-45' OR code = 'SPO-045';
UPDATE public.stores SET cep = '18130-970', city = 'São Roque', state = 'SP', address = 'Rodovia Castello Branco, km 60 - Dona Catarina (OUTLET CATARINA FASHION)' WHERE id = 'store-46' OR code = 'SPO-046';
UPDATE public.stores SET cep = '13280-000', city = 'Vinhedo', state = 'SP', address = 'Avenida Independência, 5800 - Vinhedo (Vinhedo Open Mall)' WHERE id = 'store-47' OR code = 'SPO-047';
UPDATE public.stores SET cep = '07252-312', city = 'Guarulhos', state = 'SP', address = 'Estrada do Caminho Velho, 5308 - Jardim Nova Cidade (SHOPPING BONSUCESSO)' WHERE id = 'store-48' OR code = 'SPO-048';
UPDATE public.stores SET cep = '37550-000', city = 'Pouso Alegre', state = 'MG', address = 'Rodovia Juscelino Kubitschek de Oliveira, km 107 - Pouso Alegre (Serra Sul Shopping)' WHERE id = 'store-49' OR code = 'SPO-049';
UPDATE public.stores SET cep = '01000-000', city = 'Poços de Caldas', state = 'MG', address = 'SPOLETO PARTAGE POÇOS DE CALDAS - Poços de Caldas/MG' WHERE id = 'store-50' OR code = 'SPO-050';
UPDATE public.stores SET cep = '02998-050', city = 'São Paulo', state = 'SP', address = 'Avenida Raimundo Pereira de Magalhães, 11001 - Jardim Pirituba (CANTAREIRA NORTE SHOPPING)' WHERE id = 'store-51' OR code = 'SPO-051';
UPDATE public.stores SET cep = '13845-373', city = 'Mogi Guaçu', state = 'SP', address = 'Rua Francisco Franco de Godoy Bueno, 801 - Cidade Nova Mogi Guaçu (SHOPPING BURITI MOGI GUACU)' WHERE id = 'store-52' OR code = 'SPO-052';
UPDATE public.stores SET cep = '12916-900', city = 'Bragança Paulista', state = 'SP', address = 'Rodovia Alkindar Monteiro Junqueira, km 53 - Quinta da Baronesa (SHOPPING BRAGANCA GARDEN)' WHERE id = 'store-53' OR code = 'SPO-053';
UPDATE public.stores SET cep = '13055-900', city = 'Campinas', state = 'SP', address = 'Rodovia Santos Dumont, km 66 - Parque Viracopos (Aeroporto de Viracopos)' WHERE id = 'store-54' OR code = 'SPO-054';
UPDATE public.stores SET cep = '01000-000', city = 'Barueri', state = 'SP', address = 'SPOLETO PARQUE SHOPPING BARUERI - Barueri/SP' WHERE id = 'store-55' OR code = 'SPO-055';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING TOP CENTER - São Paulo/SP' WHERE id = 'store-56' OR code = 'SPO-056';
UPDATE public.stores SET cep = '09080-510', city = 'Santo André', state = 'SP', address = 'Avenida Industrial, 600 - Jardim (GRAND PLAZA SHOPPING)' WHERE id = 'store-57' OR code = 'SPO-057';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO PAMPLONA SHOPPING - São Paulo/SP' WHERE id = 'store-58' OR code = 'SPO-058';
UPDATE public.stores SET cep = '71219-900', city = 'Brasília', state = 'DF', address = 'SMAS Trecho 1 - Guará (PARK SHOPPING SAO CAETANO)' WHERE id = 'store-59' OR code = 'SPO-059';
UPDATE public.stores SET cep = '05716-090', city = 'São Paulo', state = 'SP', address = 'Rua Itacaiúna, 61 - Vila Andrade (SHOPPING JARDIM SUL)' WHERE id = 'store-60' OR code = 'SPO-060';
UPDATE public.stores SET cep = '03086-000', city = 'São Paulo', state = 'SP', address = 'Rua Melo Freire, s/n - Tatuapé (SHOPPING METRO TATUAPE)' WHERE id = 'store-61' OR code = 'SPO-061';
UPDATE public.stores SET cep = '02305-000', city = 'São Paulo', state = 'SP', address = 'Avenida Doutor Antonio Maria Laet, 566 - Parada Inglesa (SHOPPING METRO TUCURUVI)' WHERE id = 'store-62' OR code = 'SPO-062';
UPDATE public.stores SET cep = '13059-587', city = 'Campinas', state = 'SP', address = 'Avenida John Boyd Dunlop, 3900 - Jardim Ipaussurama (PARQUE DAS BANDEIRAS)' WHERE id = 'store-63' OR code = 'SPO-063';
UPDATE public.stores SET cep = '04551-000', city = 'São Paulo', state = 'SP', address = 'Rua Olimpíadas, 360 - Vila Olímpia (SHOPPING VILA OLIMPIA)' WHERE id = 'store-64' OR code = 'SPO-064';
UPDATE public.stores SET cep = '05477-000', city = 'São Paulo', state = 'SP', address = 'Avenida das Nações Unidas, 4777 - Alto de Pinheiros (SHOPPING VILLA LOBOS MM)' WHERE id = 'store-65' OR code = 'SPO-065';
UPDATE public.stores SET cep = '02910-000', city = 'São Paulo', state = 'SP', address = 'Avenida Raimundo Pereira de Magalhães, 1465 - Jardim Iris (TIETE PLAZA SHOPPING)' WHERE id = 'store-66' OR code = 'SPO-066';
UPDATE public.stores SET cep = '01000-000', city = 'Cajamar', state = 'SP', address = 'SPOLETO SHOPPING ANHANGUERA CAJAMAR - Cajamar/SP' WHERE id = 'store-67' OR code = 'SPO-067';
UPDATE public.stores SET cep = '01000-000', city = 'Sumaré', state = 'SP', address = 'SPOLETO SHOPPING PARKCITY SUMARÉ - Sumaré/SP' WHERE id = 'store-68' OR code = 'SPO-068';
UPDATE public.stores SET cep = '13091-901', city = 'Campinas', state = 'SP', address = 'Rodovia Dom Pedro I, km 131,5 - Jardim Nilópolis (SHOPPING GALLERIA CAMPINAS)' WHERE id = 'store-69' OR code = 'SPO-069';
UPDATE public.stores SET cep = '04707-000', city = 'São Paulo', state = 'SP', address = 'Avenida Doutor Chucri Zaidan, 902 - Vila Cordeiro (SHOPPING MARKET PLACE)' WHERE id = 'store-70' OR code = 'SPO-070';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO PARQUE DA CIDADE - São Paulo/SP' WHERE id = 'store-71' OR code = 'SPO-071';
UPDATE public.stores SET cep = '06455-000', city = 'Barueri', state = 'SP', address = 'Alameda Rio Negro, 111 - Alphaville (SHOPPING IGUATEMI ALPHAVILLE)' WHERE id = 'store-72' OR code = 'SPO-072';
UPDATE public.stores SET cep = '04707-900', city = 'São Paulo', state = 'SP', address = 'Avenida Roque Petroni Júnior, 1089 - Jardim das Acácias (MORUMBI TOWN)' WHERE id = 'store-73' OR code = 'SPO-073';
UPDATE public.stores SET cep = '01238-010', city = 'São Paulo', state = 'SP', address = 'Avenida Higienópolis, 618 - Higienópolis (SHOPPING HIGIENOPOLIS)' WHERE id = 'store-74' OR code = 'SPO-074';
UPDATE public.stores SET cep = '13050-009', city = 'Campinas', state = 'SP', address = 'Rua Jacy Teixeira de Camargo, 940 - Jardim do Lago (CAMPINAS SHOPPING)' WHERE id = 'store-75' OR code = 'SPO-075';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING LIGHT - São Paulo/SP' WHERE id = 'store-76' OR code = 'SPO-076';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING JK IGUATEMI - São Paulo/SP' WHERE id = 'store-77' OR code = 'SPO-077';
UPDATE public.stores SET cep = '03086-000', city = 'São Paulo', state = 'SP', address = 'Rua Melo Freire, s/n - Tatuapé (SHOPPING BOULEVARD TATUAPE)' WHERE id = 'store-78' OR code = 'SPO-078';
UPDATE public.stores SET cep = '04707-900', city = 'São Paulo', state = 'SP', address = 'Avenida Roque Petroni Júnior, 1089 - Jardim das Acácias (SHOPPING MORUMBI)' WHERE id = 'store-79' OR code = 'SPO-079';
UPDATE public.stores SET cep = '01000-000', city = 'Hortolândia', state = 'SP', address = 'SPOLETO HORTOLÂNDIA - Hortolândia/SP' WHERE id = 'store-80' OR code = 'SPO-080';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO ROSARIO MM - Rio de Janeiro/RJ' WHERE id = 'store-81' OR code = 'SPO-081';
UPDATE public.stores SET cep = '27511-300', city = 'Resende', state = 'RJ', address = 'Avenida Saturnino Braga, 369 - Centro (RESENDE SHOPPING)' WHERE id = 'store-82' OR code = 'SPO-082';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO SHOPPING METROPOLITANO - Rio de Janeiro/RJ' WHERE id = 'store-83' OR code = 'SPO-083';
UPDATE public.stores SET cep = '27259-250', city = 'Volta Redonda', state = 'RJ', address = 'Rodovia dos Metalúrgicos, 1189 - São Geraldo (SHOPPING PARK SUL VR)' WHERE id = 'store-84' OR code = 'SPO-084';
UPDATE public.stores SET cep = '01000-000', city = 'Volta Redonda', state = 'RJ', address = 'SPOLETO VOLTA REDONDA MM - Volta Redonda/RJ' WHERE id = 'store-85' OR code = 'SPO-085';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO AEROPORTO TOM JOBIM - Rio de Janeiro/RJ' WHERE id = 'store-86' OR code = 'SPO-086';
UPDATE public.stores SET cep = '22730-001', city = 'Rio de Janeiro', state = 'RJ', address = 'Estrada do Rodrigues Caldas, 100 - Taquara (TAQUARA PLAZA)' WHERE id = 'store-87' OR code = 'SPO-087';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO OUTLET WASHINGTON LUIZ MM - Rio de Janeiro/RJ' WHERE id = 'store-88' OR code = 'SPO-088';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO RUA BUENOS AIRES - Rio de Janeiro/RJ' WHERE id = 'store-89' OR code = 'SPO-089';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO SHOPPING AMERICAS - Rio de Janeiro/RJ' WHERE id = 'store-90' OR code = 'SPO-090';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO TERMINAL RODOVIARIO NOVO RIO - Rio de Janeiro/RJ' WHERE id = 'store-91' OR code = 'SPO-091';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO PICCOLO GUANABARA RECREI - São Paulo/SP' WHERE id = 'store-92' OR code = 'SPO-092';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO RUA RB1 - Rio de Janeiro/RJ' WHERE id = 'store-93' OR code = 'SPO-093';
UPDATE public.stores SET cep = '21210-623', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida Vicente de Carvalho, 909 - Vila da Penha (CARIOCA SHOPPING)' WHERE id = 'store-94' OR code = 'SPO-094';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO SHOPPING GAVEA - Rio de Janeiro/RJ' WHERE id = 'store-95' OR code = 'SPO-095';
UPDATE public.stores SET cep = '01000-000', city = 'Nova Iguaçu', state = 'RJ', address = 'SPOLETO NOVA IGUACU RUA MM - Nova Iguaçu/RJ' WHERE id = 'store-96' OR code = 'SPO-096';
UPDATE public.stores SET cep = '25085-009', city = 'Duque de Caxias', state = 'RJ', address = 'Rodovia Washington Luiz, 2895 - Parque Duque (CAXIAS SHOPPING 2 MM)' WHERE id = 'store-97' OR code = 'SPO-097';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO RUA MARIZ E BARROS - Rio de Janeiro/RJ' WHERE id = 'store-98' OR code = 'SPO-098';
UPDATE public.stores SET cep = '01000-000', city = 'Nova Iguaçu', state = 'RJ', address = 'SPOLETO SHOPPING NOVA IGUACU - Nova Iguaçu/RJ' WHERE id = 'store-99' OR code = 'SPO-099';
UPDATE public.stores SET cep = '26255-290', city = 'Nova Iguaçu', state = 'RJ', address = 'Avenida Governador Roberto Silveira, 540 - Centro (TOP SHOPPING MM)' WHERE id = 'store-100' OR code = 'SPO-100';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO SHOPPING JACAREPAGUA - Rio de Janeiro/RJ' WHERE id = 'store-101' OR code = 'SPO-101';
UPDATE public.stores SET cep = '01000-000', city = 'Volta Redonda', state = 'RJ', address = 'SPOLETO SHOPPING VOLTA REDONDA - Volta Redonda/RJ' WHERE id = 'store-102' OR code = 'SPO-102';
UPDATE public.stores SET cep = '07252-312', city = 'Guarulhos', state = 'SP', address = 'Estrada do Caminho Velho, 5308 - Jardim Nova Cidade (BONSUCESSO RUA MM)' WHERE id = 'store-103' OR code = 'SPO-103';
UPDATE public.stores SET cep = '01000-000', city = 'Duque de Caxias', state = 'RJ', address = 'SPOLETO CAXIAS RUA - Duque de Caxias/RJ' WHERE id = 'store-104' OR code = 'SPO-104';
UPDATE public.stores SET cep = '21921-000', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida Maestro Paulo e Silva, 400 - Jardim Carioca (ILHA PLAZA SHOPPING)' WHERE id = 'store-105' OR code = 'SPO-105';
UPDATE public.stores SET cep = '72876-900', city = 'Valparaíso de Goiás', state = 'GO', address = 'Rodovia BR-040, km 12 - Parque Esplanada III (SHOPPING SULACAP)' WHERE id = 'store-106' OR code = 'SPO-106';
UPDATE public.stores SET cep = '22775-904', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida Ayrton Senna, 2150 - Barra da Tijuca (CASA SHOPPING)' WHERE id = 'store-107' OR code = 'SPO-107';
UPDATE public.stores SET cep = '21660-000', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida Brasil, 22155 - Guadalupe (JARDIM GUADALUPE 2)' WHERE id = 'store-108' OR code = 'SPO-108';
UPDATE public.stores SET cep = '22793-080', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida das Américas, 7607 - Barra da Tijuca (SHOPPING NOVO LEBLON)' WHERE id = 'store-109' OR code = 'SPO-109';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO GUANABARA BARRA - Rio de Janeiro/RJ' WHERE id = 'store-110' OR code = 'SPO-110';
UPDATE public.stores SET cep = '01000-000', city = 'Arcoverde', state = 'PE', address = 'SPOLETO ARCOVERDE - Arcoverde/PE' WHERE id = 'store-111' OR code = 'SPO-111';
UPDATE public.stores SET cep = '01000-000', city = 'Foz do Iguaçu', state = 'PR', address = 'SPOLETO CATARATAS JL SHOPPING - Foz do Iguaçu/PR' WHERE id = 'store-112' OR code = 'SPO-112';
UPDATE public.stores SET cep = '01000-000', city = 'Balneário Camboriú', state = 'SC', address = 'SPOLETO ATLANTICO - Balneário Camboriú/SC' WHERE id = 'store-113' OR code = 'SPO-113';
UPDATE public.stores SET cep = '01000-000', city = 'Londrina', state = 'PR', address = 'SPOLETO AURORA SHOPPING LONDRINA - Londrina/PR' WHERE id = 'store-114' OR code = 'SPO-114';
UPDATE public.stores SET cep = '01000-000', city = 'Blumenau', state = 'SC', address = 'SPOLETO BLUMENAU - Blumenau/SC' WHERE id = 'store-115' OR code = 'SPO-115';
UPDATE public.stores SET cep = '71219-900', city = 'Brasília', state = 'DF', address = 'SMAS Trecho 1 - Guará (CONTINENTE PARK SHOPPING)' WHERE id = 'store-116' OR code = 'SPO-116';
UPDATE public.stores SET cep = '01000-000', city = 'Florianópolis', state = 'SC', address = 'SPOLETO FLORIPA SHOPPING - Florianópolis/SC' WHERE id = 'store-117' OR code = 'SPO-117';
UPDATE public.stores SET cep = '01000-000', city = 'Itajaí', state = 'SC', address = 'SPOLETO ITAJAÍ MM - Itajaí/SC' WHERE id = 'store-118' OR code = 'SPO-118';
UPDATE public.stores SET cep = '01000-000', city = 'Cascavel', state = 'PR', address = 'SPOLETO J L SHOPPING CASCAVEL - Cascavel/PR' WHERE id = 'store-119' OR code = 'SPO-119';
UPDATE public.stores SET cep = '01000-000', city = 'Florianópolis', state = 'SC', address = 'SPOLETO SHOPPING BEIRA MAR - Florianópolis/SC' WHERE id = 'store-120' OR code = 'SPO-120';
UPDATE public.stores SET cep = '01000-000', city = 'Maringá', state = 'PR', address = 'SPOLETO SHOPPING CATUAÍ MARINGÁ - Maringá/PR' WHERE id = 'store-121' OR code = 'SPO-121';
UPDATE public.stores SET cep = '01000-000', city = 'Guarapuava', state = 'PR', address = 'SPOLETO SHOPPING CIDADE DOS LAGOS - Guarapuava/PR' WHERE id = 'store-122' OR code = 'SPO-122';
UPDATE public.stores SET cep = '01000-000', city = 'Porto Alegre', state = 'RS', address = 'SPOLETO SHOPPING IGUATEMI PORTO ALEGRE - Porto Alegre/RS' WHERE id = 'store-123' OR code = 'SPO-123';
UPDATE public.stores SET cep = '01000-000', city = 'Maringá', state = 'PR', address = 'SPOLETO SHOPPING MARINGA - Maringá/PR' WHERE id = 'store-124' OR code = 'SPO-124';
UPDATE public.stores SET cep = '01000-000', city = 'Chapecó', state = 'SC', address = 'SPOLETO SHOPPING PATIO CHAPECO - Chapecó/SC' WHERE id = 'store-125' OR code = 'SPO-125';
UPDATE public.stores SET cep = '01000-000', city = 'Umuarama', state = 'PR', address = 'SPOLETO UMUARAMA - Umuarama/PR' WHERE id = 'store-126' OR code = 'SPO-126';
UPDATE public.stores SET cep = '05005-000', city = 'São Paulo', state = 'SP', address = 'Rua Palestra Itália, 500 - Perdizes (BOURBON SHOPPING IPIRANGA)' WHERE id = 'store-127' OR code = 'SPO-127';
UPDATE public.stores SET cep = '01000-000', city = 'Cascavel', state = 'PR', address = 'SPOLETO CATUAÍ CASCAVEL - Cascavel/PR' WHERE id = 'store-128' OR code = 'SPO-128';
UPDATE public.stores SET cep = '71219-900', city = 'Brasília', state = 'DF', address = 'SMAS Trecho 1 - Guará (PARK SHOPPING CANOAS)' WHERE id = 'store-129' OR code = 'SPO-129';
UPDATE public.stores SET cep = '01000-000', city = 'Pato Branco', state = 'PR', address = 'SPOLETO PB SHOPPING PATO BRANCO - Pato Branco/PR' WHERE id = 'store-130' OR code = 'SPO-130';
UPDATE public.stores SET cep = '01000-000', city = 'Novo Hamburgo', state = 'RS', address = 'SPOLETO SHOPPING NOVO HAMBURGO - Novo Hamburgo/RS' WHERE id = 'store-131' OR code = 'SPO-131';
UPDATE public.stores SET cep = '01000-000', city = 'Campo Mourão', state = 'PR', address = 'SPOLETO SHOPPING CAMPO MOURÃO - Campo Mourão/PR' WHERE id = 'store-132' OR code = 'SPO-132';
UPDATE public.stores SET cep = '01000-000', city = 'Curitiba', state = 'PR', address = 'SPOLETO SHOPPING MUELLER - Curitiba/PR' WHERE id = 'store-133' OR code = 'SPO-133';
UPDATE public.stores SET cep = '71219-900', city = 'Brasília', state = 'DF', address = 'SMAS Trecho 1 - Guará (PARK SHOPPING BARIGUI)' WHERE id = 'store-134' OR code = 'SPO-134';
UPDATE public.stores SET cep = '01000-000', city = 'Curitiba', state = 'PR', address = 'SPOLETO SHOPPING ESTAÇÃO CURITIBA - Curitiba/PR' WHERE id = 'store-135' OR code = 'SPO-135';
UPDATE public.stores SET cep = '01000-000', city = 'Curitiba', state = 'PR', address = 'SPOLETO PALLADIUM CURITIBA - Curitiba/PR' WHERE id = 'store-136' OR code = 'SPO-136';
UPDATE public.stores SET cep = '01000-000', city = 'Joinville', state = 'SC', address = 'SPOLETO JOINVILLE MM (DELIVERY) - Joinville/SC' WHERE id = 'store-137' OR code = 'SPO-137';
UPDATE public.stores SET cep = '01000-000', city = 'Florianópolis', state = 'SC', address = 'SPOLETO VILLA ROMANA - Florianópolis/SC' WHERE id = 'store-138' OR code = 'SPO-138';
UPDATE public.stores SET cep = '01000-000', city = 'Ponta Grossa', state = 'PR', address = 'SPOLETO CAMPO GERAIS PONTA GROSSA - Ponta Grossa/PR' WHERE id = 'store-139' OR code = 'SPO-139';
UPDATE public.stores SET cep = '01000-000', city = 'Maringá', state = 'PR', address = 'SPOLETO RUA MARINGÁ - Maringá/PR' WHERE id = 'store-140' OR code = 'SPO-140';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING FREI CANECA - São Paulo/SP' WHERE id = 'store-141' OR code = 'SPO-141';
UPDATE public.stores SET cep = '01109-010', city = 'São Paulo', state = 'SP', address = 'Avenida Cruzeiro do Sul, 1100 - Canindé (SHOPPING D)' WHERE id = 'store-142' OR code = 'SPO-142';
UPDATE public.stores SET cep = '13484-015', city = 'Limeira', state = 'SP', address = 'Avenida Carlos Kuntz Busch, 800 - Parque Egisto Ragazzo (LIMEIRA)' WHERE id = 'store-143' OR code = 'SPO-143';
UPDATE public.stores SET cep = '01000-000', city = 'Americana', state = 'SP', address = 'SPOLETO AMERICANA - Americana/SP' WHERE id = 'store-144' OR code = 'SPO-144';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING BOAVISTA - São Paulo/SP' WHERE id = 'store-145' OR code = 'SPO-145';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO TRIMAIS PLACES - São Paulo/SP' WHERE id = 'store-146' OR code = 'SPO-146';
UPDATE public.stores SET cep = '01109-010', city = 'São Paulo', state = 'SP', address = 'Avenida Cruzeiro do Sul, 1100 - Canindé (SHOPPING DOM PEDRO)' WHERE id = 'store-147' OR code = 'SPO-147';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO CARREFOUR MARGINAL PINHEIROS - São Paulo/SP' WHERE id = 'store-148' OR code = 'SPO-148';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING GRANJA VIANNA - São Paulo/SP' WHERE id = 'store-149' OR code = 'SPO-149';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO POSTO LAGO AZUL - São Paulo/SP' WHERE id = 'store-150' OR code = 'SPO-150';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO EXTRA ANHANGUERA - São Paulo/SP' WHERE id = 'store-151' OR code = 'SPO-151';
UPDATE public.stores SET cep = '01000-000', city = 'Itupeva', state = 'SP', address = 'SPOLETO OUTLET PREMIUM ITUPEVA - Itupeva/SP' WHERE id = 'store-152' OR code = 'SPO-152';
UPDATE public.stores SET cep = '79021-000', city = 'Campo Grande', state = 'MS', address = 'Avenida Afonso Pena, 4909 - Santa Fé (CAMPO GRANDE MS)' WHERE id = 'store-153' OR code = 'SPO-153';
UPDATE public.stores SET cep = '79008-010', city = 'Campo Grande', state = 'MS', address = 'Avenida Ernesto Geisel, 2300 - Jockey Club (NORTE SUL PLAZA)' WHERE id = 'store-154' OR code = 'SPO-154';
UPDATE public.stores SET cep = '01000-000', city = 'Brasília', state = 'DF', address = 'SPOLETO TAGUATINGA PISTAO SUL - Brasília/DF' WHERE id = 'store-155' OR code = 'SPO-155';
UPDATE public.stores SET cep = '01000-000', city = 'Águas Lindas de Goiás', state = 'GO', address = 'SPOLETO ÁGUAS LINDAS SHOPPING PICCOLO - Águas Lindas de Goiás/GO' WHERE id = 'store-156' OR code = 'SPO-156';
UPDATE public.stores SET cep = '01000-000', city = 'Brasília', state = 'DF', address = 'SPOLETO SHOPPING CEILANDIA - Brasília/DF' WHERE id = 'store-157' OR code = 'SPO-157';
UPDATE public.stores SET cep = '01000-000', city = 'Campo Grande', state = 'MS', address = 'SPOLETO SHOPPING BOSQUE DOS IPES - Campo Grande/MS' WHERE id = 'store-158' OR code = 'SPO-158';
UPDATE public.stores SET cep = '79021-000', city = 'Campo Grande', state = 'MS', address = 'Avenida Afonso Pena, 4909 - Santa Fé (SHOPPING CAMPO GRANDE)' WHERE id = 'store-159' OR code = 'SPO-159';
UPDATE public.stores SET cep = '01000-000', city = 'Sinop', state = 'MT', address = 'SPOLETO SINOP MT MM - Sinop/MT' WHERE id = 'store-160' OR code = 'SPO-160';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO VILA SÃO TOMAZ - São Paulo/SP' WHERE id = 'store-161' OR code = 'SPO-161';
UPDATE public.stores SET cep = '01000-000', city = 'Goiânia', state = 'GO', address = 'SPOLETO PASSEIO DAS AGUAS SHOPPING - Goiânia/GO' WHERE id = 'store-162' OR code = 'SPO-162';
UPDATE public.stores SET cep = '01000-000', city = 'Goiânia', state = 'GO', address = 'SPOLETO BUENA VISTA - Goiânia/GO' WHERE id = 'store-163' OR code = 'SPO-163';
UPDATE public.stores SET cep = '01000-000', city = 'Brasília', state = 'DF', address = 'SPOLETO SHOPPING IGUATEMI DF - Brasília/DF' WHERE id = 'store-164' OR code = 'SPO-164';
UPDATE public.stores SET cep = '71219-900', city = 'Brasília', state = 'DF', address = 'SMAS Trecho 1 - Guará (PARK SHOPPING DF)' WHERE id = 'store-165' OR code = 'SPO-165';
UPDATE public.stores SET cep = '01000-000', city = 'Palmas', state = 'TO', address = 'SPOLETO PALMAS SHOPPING - Palmas/TO' WHERE id = 'store-166' OR code = 'SPO-166';
UPDATE public.stores SET cep = '01000-000', city = 'Palmas', state = 'TO', address = 'SPOLETO 307 SUL - Palmas/TO' WHERE id = 'store-167' OR code = 'SPO-167';
UPDATE public.stores SET cep = '01000-000', city = 'Goiânia', state = 'GO', address = 'SPOLETO SHOPPING BOUGAINVILLE - Goiânia/GO' WHERE id = 'store-168' OR code = 'SPO-168';
UPDATE public.stores SET cep = '70715-900', city = 'Brasília', state = 'DF', address = 'SCN Quadra 5 Bloco A - Asa Norte (BRASILIA SHOPPING)' WHERE id = 'store-169' OR code = 'SPO-169';
UPDATE public.stores SET cep = '74810-907', city = 'Goiânia', state = 'GO', address = 'Avenida Deputado Jamel Cecílio, 3300 - Jardim Goiás (FLAMBOYANT SHOPPING)' WHERE id = 'store-170' OR code = 'SPO-170';
UPDATE public.stores SET cep = '01000-000', city = 'Brasília', state = 'DF', address = 'SPOLETO AGUAS CLARAS MM - Brasília/DF' WHERE id = 'store-171' OR code = 'SPO-171';
UPDATE public.stores SET cep = '72015-597', city = 'Brasília', state = 'DF', address = 'QS 1 Rua 210, Lote 40 - Águas Claras (TAGUATINGA SHOPPING)' WHERE id = 'store-172' OR code = 'SPO-172';
UPDATE public.stores SET cep = '70660-000', city = 'Brasília', state = 'DF', address = 'SHCES Quadra 201 Lote 1 - Cruzeiro Novo (TERRACO SHOPPING)' WHERE id = 'store-173' OR code = 'SPO-173';
UPDATE public.stores SET cep = '70307-902', city = 'Brasília', state = 'DF', address = 'SCS Quadra 7 Bloco A - Asa Sul (PATIO BRASIL SHOPPING)' WHERE id = 'store-174' OR code = 'SPO-174';
UPDATE public.stores SET cep = '01109-010', city = 'São Paulo', state = 'SP', address = 'Avenida Cruzeiro do Sul, 1100 - Canindé (SHOPPING DF PLAZA)' WHERE id = 'store-175' OR code = 'SPO-175';
UPDATE public.stores SET cep = '01000-000', city = 'Brasília', state = 'DF', address = 'SPOLETO NOROESTE MM - Brasília/DF' WHERE id = 'store-176' OR code = 'SPO-176';
UPDATE public.stores SET cep = '22640-100', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida das Américas, 4666 - Barra da Tijuca (BARRA SHOPPING)' WHERE id = 'store-177' OR code = 'SPO-177';
UPDATE public.stores SET cep = '01109-010', city = 'São Paulo', state = 'SP', address = 'Avenida Cruzeiro do Sul, 1100 - Canindé (SHOPPING DOWNTOWN)' WHERE id = 'store-178' OR code = 'SPO-178';
UPDATE public.stores SET cep = '20511-000', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida Maracanã, 987 - Tijuca (SHOPPING TIJUCA)' WHERE id = 'store-179' OR code = 'SPO-179';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO PARK JACAREPAGUA - Rio de Janeiro/RJ' WHERE id = 'store-180' OR code = 'SPO-180';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO SHOPPING VIA PARQUE - Rio de Janeiro/RJ' WHERE id = 'store-181' OR code = 'SPO-181';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO RUA LARGO DO MACHADO - Rio de Janeiro/RJ' WHERE id = 'store-182' OR code = 'SPO-182';
UPDATE public.stores SET cep = '21310-310', city = 'Rio de Janeiro', state = 'RJ', address = 'Estrada do Portela, 222 - Madureira (MADUREIRA SHOPPING)' WHERE id = 'store-183' OR code = 'SPO-183';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO COPACABANA MM - Rio de Janeiro/RJ' WHERE id = 'store-184' OR code = 'SPO-184';
UPDATE public.stores SET cep = '29107-900', city = 'Vila Velha', state = 'ES', address = 'Avenida Luciano das Neves, 2418 - Divino Espírito Santo (Shopping Vila Velha)' WHERE id = 'store-185' OR code = 'SPO-185';
UPDATE public.stores SET cep = '01000-000', city = 'Cachoeiro de Itapemirim', state = 'ES', address = 'SPOLETO CACHOEIRO - Cachoeiro de Itapemirim/ES' WHERE id = 'store-186' OR code = 'SPO-186';
UPDATE public.stores SET cep = '01000-000', city = 'Vitória', state = 'ES', address = 'SPOLETO MASTER PLACE MALL - Vitória/ES' WHERE id = 'store-187' OR code = 'SPO-187';
UPDATE public.stores SET cep = '01000-000', city = 'Serra', state = 'ES', address = 'SPOLETO SHOPPING MESTRE ALVARO - Serra/ES' WHERE id = 'store-188' OR code = 'SPO-188';
UPDATE public.stores SET cep = '01000-000', city = 'Serra', state = 'ES', address = 'SPOLETO SHOPPING MONTSERRAT - Serra/ES' WHERE id = 'store-189' OR code = 'SPO-189';
UPDATE public.stores SET cep = '29144-000', city = 'Cariacica', state = 'ES', address = 'Rodovia BR-262, km 5 - Campo Grande (Shopping Moxuara)' WHERE id = 'store-190' OR code = 'SPO-190';
UPDATE public.stores SET cep = '29101-900', city = 'Vitória', state = 'ES', address = 'Avenida Doutor Olivio Lira, 353 - Praia da Costa (Shopping Praia da Costa)' WHERE id = 'store-191' OR code = 'SPO-191';
UPDATE public.stores SET cep = '29107-900', city = 'Vila Velha', state = 'ES', address = 'Avenida Luciano das Neves, 2418 - Divino Espírito Santo (Shopping Vila Velha)' WHERE id = 'store-192' OR code = 'SPO-192';
UPDATE public.stores SET cep = '29050-902', city = 'Vitória', state = 'ES', address = 'Avenida Américo Buaiz, 200 - Enseada do Suá (Shopping Vitória)' WHERE id = 'store-193' OR code = 'SPO-193';
UPDATE public.stores SET cep = '22790-702', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida das Américas, 19019 - Recreio dos Bandeirantes (RECREIO SHOPPING)' WHERE id = 'store-194' OR code = 'SPO-194';
UPDATE public.stores SET cep = '22640-100', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida das Américas, 4666 - Barra da Tijuca (BARRA SHOPPING 2)' WHERE id = 'store-195' OR code = 'SPO-195';
UPDATE public.stores SET cep = '25555-201', city = 'São João de Meriti', state = 'RJ', address = 'Rodovia Presidente Dutra, 4200 - Parque Barreto (SHOPPING GRANDE RIO)' WHERE id = 'store-196' OR code = 'SPO-196';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING IGUATEMI RIO - São Paulo/SP' WHERE id = 'store-197' OR code = 'SPO-197';
UPDATE public.stores SET cep = '71219-900', city = 'Brasília', state = 'DF', address = 'SMAS Trecho 1 - Guará (PARK SHOPPING CAMPO GRANDE)' WHERE id = 'store-198' OR code = 'SPO-198';
UPDATE public.stores SET cep = '23050-300', city = 'Rio de Janeiro', state = 'RJ', address = 'Estrada do Mendanha, 555 - Campo Grande (WEST SHOPPING)' WHERE id = 'store-199' OR code = 'SPO-199';
UPDATE public.stores SET cep = '01000-000', city = 'Barueri', state = 'SP', address = 'SPOLETO ALDEIA DA SERRA MM - Barueri/SP' WHERE id = 'store-200' OR code = 'SPO-200';
UPDATE public.stores SET cep = '21820-005', city = 'Rio de Janeiro', state = 'RJ', address = 'Rua Fonseca, 240 - Bangu (BANGU SHOPPING)' WHERE id = 'store-201' OR code = 'SPO-201';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO SHOPPING BARRA SQUARE - Rio de Janeiro/RJ' WHERE id = 'store-202' OR code = 'SPO-202';
UPDATE public.stores SET cep = '01000-000', city = 'Niterói', state = 'RJ', address = 'SPOLETO RUA ICARAI - Niterói/RJ' WHERE id = 'store-203' OR code = 'SPO-203';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO RUA TIJUCA MM - Rio de Janeiro/RJ' WHERE id = 'store-204' OR code = 'SPO-204';
UPDATE public.stores SET cep = '21230-043', city = 'Rio de Janeiro', state = 'RJ', address = 'Rua Itapera, 500 - Irajá (SHOPPING VIA BRASIL PICCOLO)' WHERE id = 'store-205' OR code = 'SPO-205';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO RUA ENSEADA - Rio de Janeiro/RJ' WHERE id = 'store-206' OR code = 'SPO-206';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO RUA CRUZ VERMELHA - Rio de Janeiro/RJ' WHERE id = 'store-207' OR code = 'SPO-207';
UPDATE public.stores SET cep = '41500-570', city = 'Salvador', state = 'BA', address = 'Praça Gago Coutinho, s/n - São Cristóvão (Aeroporto de Salvador)' WHERE id = 'store-208' OR code = 'SPO-208';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING BELA VISTA - São Paulo/SP' WHERE id = 'store-209' OR code = 'SPO-209';
UPDATE public.stores SET cep = '01000-000', city = 'Maracanaú', state = 'CE', address = 'SPOLETO PICCOLO MARACANAÚ MM - Maracanaú/CE' WHERE id = 'store-210' OR code = 'SPO-210';
UPDATE public.stores SET cep = '01000-000', city = 'Juazeiro do Norte', state = 'CE', address = 'SPOLETO CARIRI SHOPPING - Juazeiro do Norte/CE' WHERE id = 'store-211' OR code = 'SPO-211';
UPDATE public.stores SET cep = '01000-000', city = 'Sobral', state = 'CE', address = 'SPOLETO NORTH SHOPPING SOBRAL II - Sobral/CE' WHERE id = 'store-212' OR code = 'SPO-212';
UPDATE public.stores SET cep = '01000-000', city = 'Vitória da Conquista', state = 'BA', address = 'SPOLETO BOULEVARD VITORIA DA CONQUISTA - Vitória da Conquista/BA' WHERE id = 'store-213' OR code = 'SPO-213';
UPDATE public.stores SET cep = '01000-000', city = 'Fortaleza', state = 'CE', address = 'SPOLETO COMPACTO SHOPPING VIA SUL - Fortaleza/CE' WHERE id = 'store-214' OR code = 'SPO-214';
UPDATE public.stores SET cep = '60355-630', city = 'Fortaleza', state = 'CE', address = 'Avenida Sargento Hermínio Sampaio, 3100 - Presidente Kennedy (RioMar Kennedy)' WHERE id = 'store-215' OR code = 'SPO-215';
UPDATE public.stores SET cep = '01000-000', city = 'Fortaleza', state = 'CE', address = 'SPOLETO SHOPPING RIOMAR FORTALEZA MM - Fortaleza/CE' WHERE id = 'store-216' OR code = 'SPO-216';
UPDATE public.stores SET cep = '01000-000', city = 'Fortaleza', state = 'CE', address = 'SPOLETO SHOPPING BENFICA - Fortaleza/CE' WHERE id = 'store-217' OR code = 'SPO-217';
UPDATE public.stores SET cep = '01000-000', city = 'Fortaleza', state = 'CE', address = 'SPOLETO SHOPPING IGUATEMI FORTALEZA - Fortaleza/CE' WHERE id = 'store-218' OR code = 'SPO-218';
UPDATE public.stores SET cep = '01109-010', city = 'São Paulo', state = 'SP', address = 'Avenida Cruzeiro do Sul, 1100 - Canindé (SHOPPING DEL PASEO)' WHERE id = 'store-219' OR code = 'SPO-219';
UPDATE public.stores SET cep = '01000-000', city = 'Fortaleza', state = 'CE', address = 'SPOLETO TERRAZO SHOPPING - Fortaleza/CE' WHERE id = 'store-220' OR code = 'SPO-220';
UPDATE public.stores SET cep = '01000-000', city = 'Fortaleza', state = 'CE', address = 'SPOLETO SHOPPING PARANGABA - Fortaleza/CE' WHERE id = 'store-221' OR code = 'SPO-221';
UPDATE public.stores SET cep = '01000-000', city = 'Itabuna', state = 'BA', address = 'SPOLETO JEQUITIBA PLAZA SHOPPING - Itabuna/BA' WHERE id = 'store-222' OR code = 'SPO-222';
UPDATE public.stores SET cep = '01000-000', city = 'Vitória da Conquista', state = 'BA', address = 'SPOLETO SHOPPING CONQUISTA SUL - Vitória da Conquista/BA' WHERE id = 'store-223' OR code = 'SPO-223';
UPDATE public.stores SET cep = '01000-000', city = 'Salvador', state = 'BA', address = 'SPOLETO PICCOLO RODOVIARIA SALVADOR - Salvador/BA' WHERE id = 'store-224' OR code = 'SPO-224';
UPDATE public.stores SET cep = '01000-000', city = 'Feira de Santana', state = 'BA', address = 'SPOLETO SHOPPING FEIRA DE SANTANA - Feira de Santana/BA' WHERE id = 'store-225' OR code = 'SPO-225';
UPDATE public.stores SET cep = '01000-000', city = 'Camaçari', state = 'BA', address = 'SPOLETO PICCOLO CAMAÇARI - Camaçari/BA' WHERE id = 'store-226' OR code = 'SPO-226';
UPDATE public.stores SET cep = '01000-000', city = 'Ilhéus', state = 'BA', address = 'SPOLETO PRAIA HOTEL ILHEUS - Ilhéus/BA' WHERE id = 'store-227' OR code = 'SPO-227';
UPDATE public.stores SET cep = '13092-500', city = 'Campinas', state = 'SP', address = 'Avenida Iguatemi, 777 - Vila Brandina (SHOPPING IGUATEMI CAMPINAS)' WHERE id = 'store-228' OR code = 'SPO-228';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING PAULISTA - São Paulo/SP' WHERE id = 'store-229' OR code = 'SPO-229';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING CIDADE SAO PAULO - São Paulo/SP' WHERE id = 'store-230' OR code = 'SPO-230';
UPDATE public.stores SET cep = '05425-070', city = 'São Paulo', state = 'SP', address = 'Avenida Rebouças, 3970 - Pinheiros (SHOPPING ELDORADO)' WHERE id = 'store-231' OR code = 'SPO-231';
UPDATE public.stores SET cep = '01000-000', city = 'Guarulhos', state = 'SP', address = 'SPOLETO SHOPPING BOSQUE MAIA - Guarulhos/SP' WHERE id = 'store-232' OR code = 'SPO-232';
UPDATE public.stores SET cep = '01000-000', city = 'Guarulhos', state = 'SP', address = 'SPOLETO SHOPPING GUARULHOS - Guarulhos/SP' WHERE id = 'store-233' OR code = 'SPO-233';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING WEST PLAZA - São Paulo/SP' WHERE id = 'store-234' OR code = 'SPO-234';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING CENTER 3 - São Paulo/SP' WHERE id = 'store-235' OR code = 'SPO-235';
UPDATE public.stores SET cep = '05005-000', city = 'São Paulo', state = 'SP', address = 'Rua Palestra Itália, 500 - Perdizes (BOURBON SHOPPING)' WHERE id = 'store-236' OR code = 'SPO-236';
UPDATE public.stores SET cep = '04037-003', city = 'São Paulo', state = 'SP', address = 'Rua Domingos de Morais, 2564 - Vila Mariana (SHOPPING METRO SANTA CRUZ)' WHERE id = 'store-237' OR code = 'SPO-237';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO COMPACTO CARREFOUR LIMAO - São Paulo/SP' WHERE id = 'store-238' OR code = 'SPO-238';
UPDATE public.stores SET cep = '01000-000', city = 'Belo Horizonte', state = 'MG', address = 'SPOLETO PARQUE PRADO SP PICCOLO - Belo Horizonte/MG' WHERE id = 'store-239' OR code = 'SPO-239';
UPDATE public.stores SET cep = '13405-247', city = 'Piracicaba', state = 'SP', address = 'Avenida Limeira, 722 - Areião (SHOPPING PIRACICABA)' WHERE id = 'store-240' OR code = 'SPO-240';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO EVENTOS - RIO - Rio de Janeiro/RJ' WHERE id = 'store-241' OR code = 'SPO-241';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO RUA MEXICO - Rio de Janeiro/RJ' WHERE id = 'store-242' OR code = 'SPO-242';
UPDATE public.stores SET cep = '01000-000', city = 'Teresópolis', state = 'RJ', address = 'SPOLETO FOOD TRUCK TERESOPOLIS - Teresópolis/RJ' WHERE id = 'store-243' OR code = 'SPO-243';
UPDATE public.stores SET cep = '01000-000', city = 'São Gonçalo', state = 'RJ', address = 'SPOLETO BOULEVARD SAO GONCALO - São Gonçalo/RJ' WHERE id = 'store-244' OR code = 'SPO-244';
UPDATE public.stores SET cep = '24020-086', city = 'Niterói', state = 'RJ', address = 'Rua Quinze de Novembro, 8 - Centro (PLAZA SHOPPING NITEROI)' WHERE id = 'store-245' OR code = 'SPO-245';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO RUA LEBLON - Rio de Janeiro/RJ' WHERE id = 'store-246' OR code = 'SPO-246';
UPDATE public.stores SET cep = '01000-000', city = 'Petrópolis', state = 'RJ', address = 'SPOLETO RUA PETROPOLIS - Petrópolis/RJ' WHERE id = 'store-247' OR code = 'SPO-247';
UPDATE public.stores SET cep = '01000-000', city = 'Maricá', state = 'RJ', address = 'SPOLETO POSTO MARICA - Maricá/RJ' WHERE id = 'store-248' OR code = 'SPO-248';
UPDATE public.stores SET cep = '24445-300', city = 'São Gonçalo', state = 'RJ', address = 'Avenida São Gonçalo, 100 - Boa Vista (SAO GONCALO SHOPPING)' WHERE id = 'store-249' OR code = 'SPO-249';
UPDATE public.stores SET cep = '24020-004', city = 'Niterói', state = 'RJ', address = 'Avenida Visconde do Rio Branco, 360 - Centro (SHOPPING BAY MARKET)' WHERE id = 'store-250' OR code = 'SPO-250';
UPDATE public.stores SET cep = '22430-041', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida Afrânio de Melo Franco, 290 - Leblon (SHOPPING LEBLON)' WHERE id = 'store-251' OR code = 'SPO-251';
UPDATE public.stores SET cep = '20520-050', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida Pastor Martin Luther King Jr., 126 - Del Castilho (SHOPPING NOVA AMERICA)' WHERE id = 'store-252' OR code = 'SPO-252';
UPDATE public.stores SET cep = '20520-050', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida Pastor Martin Luther King Jr., 126 - Del Castilho (SHOPPING NOVA AMERICA II MM)' WHERE id = 'store-253' OR code = 'SPO-253';
UPDATE public.stores SET cep = '01000-000', city = 'São Gonçalo', state = 'RJ', address = 'SPOLETO SHOPPING PÁTIO ALCÂNTARA - São Gonçalo/RJ' WHERE id = 'store-254' OR code = 'SPO-254';
UPDATE public.stores SET cep = '22290-160', city = 'Rio de Janeiro', state = 'RJ', address = 'Rua Lauro Müller, 116 - Botafogo (SHOPPING RIO SUL)' WHERE id = 'store-255' OR code = 'SPO-255';
UPDATE public.stores SET cep = '01000-000', city = 'Nova Friburgo', state = 'RJ', address = 'SPOLETO FRIBURGO SHOPPING - Nova Friburgo/RJ' WHERE id = 'store-256' OR code = 'SPO-256';
UPDATE public.stores SET cep = '20770-000', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida Dom Hélder Câmara, 5474 - Cachambi (NORTE SHOPPING)' WHERE id = 'store-257' OR code = 'SPO-257';
UPDATE public.stores SET cep = '01000-000', city = 'Teresópolis', state = 'RJ', address = 'SPOLETO TERESOPOLIS SHOPPING - Teresópolis/RJ' WHERE id = 'store-258' OR code = 'SPO-258';
UPDATE public.stores SET cep = '28055-245', city = 'Campos dos Goytacazes', state = 'RJ', address = 'Avenida Doutor Silvio Bastos Tavares, 330 - Parque Leopoldina (BOULEVARD CAMPOS)' WHERE id = 'store-259' OR code = 'SPO-259';
UPDATE public.stores SET cep = '01000-000', city = 'Macaé', state = 'RJ', address = 'SPOLETO RUA MACAE CAVALEIROS - Macaé/RJ' WHERE id = 'store-260' OR code = 'SPO-260';
UPDATE public.stores SET cep = '28909-570', city = 'Cabo Frio', state = 'RJ', address = 'Avenida Henrique Terra, 1700 - Palmeiras (SHOPPING PARK LAGOS)' WHERE id = 'store-261' OR code = 'SPO-261';
UPDATE public.stores SET cep = '27930-560', city = 'Macaé', state = 'RJ', address = 'Avenida Aluisio da Silva Gomes, 800 - Granja dos Cavaleiros (SHOPPING PLAZA MACAE)' WHERE id = 'store-262' OR code = 'SPO-262';
UPDATE public.stores SET cep = '01000-000', city = 'Rio das Ostras', state = 'RJ', address = 'SPOLETO SHOPPING RIO DAS OSTRAS - Rio das Ostras/RJ' WHERE id = 'store-263' OR code = 'SPO-263';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO PENINSULA MALL - Rio de Janeiro/RJ' WHERE id = 'store-264' OR code = 'SPO-264';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO BOSSA NOVA MALL - Rio de Janeiro/RJ' WHERE id = 'store-265' OR code = 'SPO-265';
UPDATE public.stores SET cep = '22250-040', city = 'Rio de Janeiro', state = 'RJ', address = 'Praia de Botafogo, 400 - Botafogo (BOTAFOGO PRAIA SHOPPING)' WHERE id = 'store-266' OR code = 'SPO-266';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO RUA COPACABANA II - Rio de Janeiro/RJ' WHERE id = 'store-267' OR code = 'SPO-267';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO COMPACTO ITAIPU MULTICENTER - São Paulo/SP' WHERE id = 'store-268' OR code = 'SPO-268';
UPDATE public.stores SET cep = '01000-000', city = 'Rio de Janeiro', state = 'RJ', address = 'SPOLETO BOTAFOGO RUA MM - Rio de Janeiro/RJ' WHERE id = 'store-269' OR code = 'SPO-269';
UPDATE public.stores SET cep = '01109-010', city = 'São Paulo', state = 'SP', address = 'Avenida Cruzeiro do Sul, 1100 - Canindé (SHOPPING DO MEIER)' WHERE id = 'store-270' OR code = 'SPO-270';
UPDATE public.stores SET cep = '01000-000', city = 'Cabo Frio / Arraial', state = 'RJ', address = 'SPOLETO ARRAIAL DO CABO PICCOLO - Cabo Frio / Arraial/RJ' WHERE id = 'store-271' OR code = 'SPO-271';
UPDATE public.stores SET cep = '01000-000', city = 'Juiz de Fora', state = 'MG', address = 'SPOLETO INDEPENDENCIA SHOPPING - Juiz de Fora/MG' WHERE id = 'store-272' OR code = 'SPO-272';
UPDATE public.stores SET cep = '69050-010', city = 'Manaus', state = 'AM', address = 'Avenida Djalma Batista, 482 - Parque 10 de Novembro (Amazonas Shopping)' WHERE id = 'store-273' OR code = 'SPO-273';
UPDATE public.stores SET cep = '01000-000', city = 'Boa Vista', state = 'RR', address = 'SPOLETO BOA VISTA RUA - Boa Vista/RR' WHERE id = 'store-274' OR code = 'SPO-274';
UPDATE public.stores SET cep = '66053-000', city = 'Belém', state = 'PA', address = 'Avenida Visconde de Souza Franco, 776 - Reduto (Boulevard Shopping Belém)' WHERE id = 'store-275' OR code = 'SPO-275';
UPDATE public.stores SET cep = '01000-000', city = 'Belém', state = 'PA', address = 'SPOLETO CASTANHEIRAS SHOPPING - Belém/PA' WHERE id = 'store-276' OR code = 'SPO-276';
UPDATE public.stores SET cep = '01000-000', city = 'Macapá', state = 'AP', address = 'SPOLETO MACAPA SHOPPING - Macapá/AP' WHERE id = 'store-277' OR code = 'SPO-277';
UPDATE public.stores SET cep = '01000-000', city = 'Manaus', state = 'AM', address = 'SPOLETO PARK SUMAUMA - Manaus/AM' WHERE id = 'store-278' OR code = 'SPO-278';
UPDATE public.stores SET cep = '66635-110', city = 'Belém', state = 'PA', address = 'Rodovia Augusto Montenegro, 4300 - Parque Verde (Parque Shopping Belém)' WHERE id = 'store-279' OR code = 'SPO-279';
UPDATE public.stores SET cep = '01000-000', city = 'Belém', state = 'PA', address = 'SPOLETO RUA NAZARE MM - Belém/PA' WHERE id = 'store-280' OR code = 'SPO-280';
UPDATE public.stores SET cep = '01000-000', city = 'Belém', state = 'PA', address = 'SPOLETO SHOPPING GRAO PARA - Belém/PA' WHERE id = 'store-281' OR code = 'SPO-281';
UPDATE public.stores SET cep = '66025-005', city = 'Belém', state = 'PA', address = 'Travessa Padre Eutíquio, 1078 - Batista Campos (Shopping Pátio Belém)' WHERE id = 'store-282' OR code = 'SPO-282';
UPDATE public.stores SET cep = '69057-002', city = 'Manaus', state = 'AM', address = 'Avenida Mário Ypiranga, 1300 - Adrianópolis (Manauara Shopping)' WHERE id = 'store-283' OR code = 'SPO-283';
UPDATE public.stores SET cep = '01000-000', city = 'Manaus', state = 'AM', address = 'SPOLETO PONTA NEGRA - Manaus/AM' WHERE id = 'store-284' OR code = 'SPO-284';
UPDATE public.stores SET cep = '01000-000', city = 'Ananindeua', state = 'PA', address = 'SPOLETO SHOPPING ANANINDEUA - Ananindeua/PA' WHERE id = 'store-285' OR code = 'SPO-285';
UPDATE public.stores SET cep = '01109-010', city = 'São Paulo', state = 'SP', address = 'Avenida Cruzeiro do Sul, 1100 - Canindé (SHOPPING DA ILHA)' WHERE id = 'store-286' OR code = 'SPO-286';
UPDATE public.stores SET cep = '01000-000', city = 'São Luís', state = 'MA', address = 'SPOLETO SÃO LUIS SHOPPING - São Luís/MA' WHERE id = 'store-287' OR code = 'SPO-287';
UPDATE public.stores SET cep = '01000-000', city = 'Manaus', state = 'AM', address = 'SPOLETO VIA NORTE - Manaus/AM' WHERE id = 'store-288' OR code = 'SPO-288';
UPDATE public.stores SET cep = '01000-000', city = 'Manaus', state = 'AM', address = 'SPOLETO MANAUS PLAZA - Manaus/AM' WHERE id = 'store-289' OR code = 'SPO-289';
UPDATE public.stores SET cep = '01000-000', city = 'Teresina', state = 'PI', address = 'SPOLETO SHOPPING RIO POTY - Teresina/PI' WHERE id = 'store-290' OR code = 'SPO-290';
UPDATE public.stores SET cep = '01000-000', city = 'Teresina', state = 'PI', address = 'SPOLETO TERESINA SHOPPING - Teresina/PI' WHERE id = 'store-291' OR code = 'SPO-291';
UPDATE public.stores SET cep = '01000-000', city = 'Porto Velho', state = 'RO', address = 'SPOLETO PORTO VELHO SHOPPING - Porto Velho/RO' WHERE id = 'store-292' OR code = 'SPO-292';
UPDATE public.stores SET cep = '01000-000', city = 'Porto Velho', state = 'RO', address = 'SPOLETO PORTO VELHO DK - Porto Velho/RO' WHERE id = 'store-293' OR code = 'SPO-293';
UPDATE public.stores SET cep = '01000-000', city = 'Porto Velho', state = 'RO', address = 'SPOLETO DK PORTO VELHO - Porto Velho/RO' WHERE id = 'store-294' OR code = 'SPO-294';
UPDATE public.stores SET cep = '20770-000', city = 'Rio de Janeiro', state = 'RJ', address = 'Avenida Dom Hélder Câmara, 5474 - Cachambi (PATIO NORTE SHOPPING)' WHERE id = 'store-295' OR code = 'SPO-295';
UPDATE public.stores SET cep = '01000-000', city = 'Rio Branco', state = 'AC', address = 'SPOLETO RIO BRANCO - Rio Branco/AC' WHERE id = 'store-296' OR code = 'SPO-296';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO JABAQUARA PICCOLO MM - São Paulo/SP' WHERE id = 'store-297' OR code = 'SPO-297';
UPDATE public.stores SET cep = '09751-000', city = 'São Bernardo do Campo', state = 'SP', address = 'Avenida Kennedy, 700 - Jardim do Mar (GOLDEN SQUARE SHOPPING)' WHERE id = 'store-298' OR code = 'SPO-298';
UPDATE public.stores SET cep = '09111-340', city = 'Santo André', state = 'SP', address = 'Rua Giovanni Battista Pirelli, 155 - Novo Homero Thon (ATRIUM SHOPPING SANTO ANDRE)' WHERE id = 'store-299' OR code = 'SPO-299';
UPDATE public.stores SET cep = '09040-310', city = 'Santo André', state = 'SP', address = 'Avenida Pereira Barreto, 42 - Vila Gilda (SHOPPING ABC)' WHERE id = 'store-300' OR code = 'SPO-300';
UPDATE public.stores SET cep = '11440-530', city = 'Guarujá', state = 'SP', address = 'Avenida Miguel Estefno - Enseada (GUARUJÁ)' WHERE id = 'store-301' OR code = 'SPO-301';
UPDATE public.stores SET cep = '09781-220', city = 'São Bernardo do Campo', state = 'SP', address = 'Avenida Rotary, 624 - Ferrazópolis (SAO BERNARDO PLAZA SHOPPING)' WHERE id = 'store-302' OR code = 'SPO-302';
UPDATE public.stores SET cep = '11310-060', city = 'São Vicente', state = 'SP', address = 'Rua Frei Gaspar, 365 - Centro (BRISAMAR SHOPPING)' WHERE id = 'store-303' OR code = 'SPO-303';
UPDATE public.stores SET cep = '03153-002', city = 'São Paulo', state = 'SP', address = 'Avenida Doutor Francisco Mesquita, 1000 - Jardim Ibitirama (CENTRAL PLAZA SHOPPING)' WHERE id = 'store-304' OR code = 'SPO-304';
UPDATE public.stores SET cep = '08590-500', city = 'Itaquaquecetuba', state = 'SP', address = 'Estrada do Ribeiro - Ribeiro (OUTLET PREMIUM GRANDE SP)' WHERE id = 'store-305' OR code = 'SPO-305';
UPDATE public.stores SET cep = '09390-120', city = 'Mauá', state = 'SP', address = 'Avenida Antônia Rosa Fioravanti - Jardim Rosina (MAUA PLAZA SHOPPING)' WHERE id = 'store-306' OR code = 'SPO-306';
UPDATE public.stores SET cep = '08710-500', city = 'Mogi das Cruzes', state = 'SP', address = 'Avenida Voluntário Fernando Pinheiro Franco, 515 - Centro (PATTEO URUPEMA)' WHERE id = 'store-307' OR code = 'SPO-307';
UPDATE public.stores SET cep = '11700-005', city = 'Praia Grande', state = 'SP', address = 'Avenida Ayrton Senna da Silva, 1511 - Xixová (LITORAL PLAZA SHOPPING)' WHERE id = 'store-308' OR code = 'SPO-308';
UPDATE public.stores SET cep = '12589-899', city = 'Roseira', state = 'SP', address = 'Área Rural - Área Rural de Roseira (POSTO ARCO IRIS)' WHERE id = 'store-309' OR code = 'SPO-309';
UPDATE public.stores SET cep = '08220-380', city = 'São Paulo', state = 'SP', address = 'Avenida José Pinheiro Borges, s/n - Itaquera (SHOPPING METRO ITAQUERA)' WHERE id = 'store-310' OR code = 'SPO-310';
UPDATE public.stores SET cep = '11035-900', city = 'Santos', state = 'SP', address = 'Rua Alexandre Martins, 80 - Aparecida (PRAIAMAR SHOPPING)' WHERE id = 'store-311' OR code = 'SPO-311';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SANTANA PARQUE SHOPPING MM - São Paulo/SP' WHERE id = 'store-312' OR code = 'SPO-312';
UPDATE public.stores SET cep = '11013-001', city = 'Santos', state = 'SP', address = 'Avenida João Pessoa - Centro (SANTOS RUA)' WHERE id = 'store-313' OR code = 'SPO-313';
UPDATE public.stores SET cep = '03337-000', city = 'São Paulo', state = 'SP', address = 'Avenida Regente Feijó, 1739 - Tatuapé (SHOPPING ANALIA FRANCO)' WHERE id = 'store-314' OR code = 'SPO-314';
UPDATE public.stores SET cep = '03527-900', city = 'São Paulo', state = 'SP', address = 'Avenida Aricanduva, 5555 - Vila Matilde (SHOPPING ARICANDUVA)' WHERE id = 'store-315' OR code = 'SPO-315';
UPDATE public.stores SET cep = '12505-211', city = 'Guaratinguetá', state = 'SP', address = 'Rua Theobaldo Verri - Vila Jacobelli (SHOPPING BURITI GUARA)' WHERE id = 'store-316' OR code = 'SPO-316';
UPDATE public.stores SET cep = '02089-900', city = 'São Paulo', state = 'SP', address = 'Travessa Casalbuono, 120 - Vila Guilherme (SHOPPING CENTER NORTE)' WHERE id = 'store-317' OR code = 'SPO-317';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING LED BARRA FUNDA - São Paulo/SP' WHERE id = 'store-318' OR code = 'SPO-318';
UPDATE public.stores SET cep = '09751-040', city = 'São Bernardo do Campo', state = 'SP', address = 'Rua Itú, 200 - Baeta Neves (SHOPPING METROPOLE)' WHERE id = 'store-319' OR code = 'SPO-319';
UPDATE public.stores SET cep = '03106-010', city = 'São Paulo', state = 'SP', address = 'Rua Capitão Pacheco e Chaves, 313 - Mooca (MOOCA PLAZA SHOPPING)' WHERE id = 'store-320' OR code = 'SPO-320';
UPDATE public.stores SET cep = '11055-300', city = 'Santos', state = 'SP', address = 'Avenida Ana Costa, 549 - Gonzaga (SHOPPING PARQUE BALNEARIO)' WHERE id = 'store-321' OR code = 'SPO-321';
UPDATE public.stores SET cep = '12421-681', city = 'Pindamonhangaba', state = 'SP', address = 'Rua Alcides Ramos Nogueira, 650 - Nossa Senhora do Perpétuo Socorro (SHOPPING PATIO PINDA)' WHERE id = 'store-322' OR code = 'SPO-322';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO SHOPPING ALEGRIA - São Paulo/SP' WHERE id = 'store-323' OR code = 'SPO-323';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO PICCOLO HIPER ANDORINHA - São Paulo/SP' WHERE id = 'store-324' OR code = 'SPO-324';
UPDATE public.stores SET cep = '03527-900', city = 'São Paulo', state = 'SP', address = 'Avenida Aricanduva, 5555 - Vila Matilde (CARREFOUR ARICANDUVA)' WHERE id = 'store-325' OR code = 'SPO-325';
UPDATE public.stores SET cep = '14403-900', city = 'Franca', state = 'SP', address = 'Avenida Rio Amazonas, 4001 - Parque Francal (FRANCA)' WHERE id = 'store-326' OR code = 'SPO-326';
UPDATE public.stores SET cep = '14027-250', city = 'Ribeirão Preto', state = 'SP', address = 'Avenida Luiz Eduardo Toledo Prado, 900 - Vila do Golf (IGUATEMI RIBEIRAO PRETO)' WHERE id = 'store-327' OR code = 'SPO-327';
UPDATE public.stores SET cep = '08780-560', city = 'Mogi das Cruzes', state = 'SP', address = 'Praça Dezoito de Junho, 1001 - Jardim Armênia (MOGI SHOPPING)' WHERE id = 'store-328' OR code = 'SPO-328';
UPDATE public.stores SET cep = '14096-902', city = 'Ribeirão Preto', state = 'SP', address = 'Avenida Presidente Kennedy, 1500 - Ribeirânia (NOVO SHOPPING)' WHERE id = 'store-329' OR code = 'SPO-329';
UPDATE public.stores SET cep = '06710-610', city = 'Cotia', state = 'SP', address = 'Rua Monte Alegre, km 22 - Jardim Rebelato (OPEN SQUARE)' WHERE id = 'store-330' OR code = 'SPO-330';
UPDATE public.stores SET cep = '06016-060', city = 'Osasco', state = 'SP', address = 'Rua Tenente Avelar Pires de Azevedo, 81 - Centro (OSASCO PLAZA SHOPPING)' WHERE id = 'store-331' OR code = 'SPO-331';
UPDATE public.stores SET cep = '06020-012', city = 'Osasco', state = 'SP', address = 'Avenida dos Autonomistas - Vila Yara (CONTINENTAL SHOPPING)' WHERE id = 'store-332' OR code = 'SPO-332';
UPDATE public.stores SET cep = '03632-000', city = 'São Paulo', state = 'SP', address = 'Rua Doutor João Ribeiro, 304 - Penha (PENHA SHOPPING)' WHERE id = 'store-333' OR code = 'SPO-333';
UPDATE public.stores SET cep = '14026-900', city = 'Ribeirão Preto', state = 'SP', address = 'Avenida Coronel Fernando Ferreira Leite, 1540 - Jardim Califórnia (RIBEIRAO SHOPPING)' WHERE id = 'store-334' OR code = 'SPO-334';
UPDATE public.stores SET cep = '11672-390', city = 'Caraguatatuba', state = 'SP', address = 'Alameda dos Golfinhos Vermelhos, 1086 - Pontal de Santa Marina (SERRAMAR PARQUE SHOPPING)' WHERE id = 'store-335' OR code = 'SPO-335';
UPDATE public.stores SET cep = '05512-900', city = 'São Paulo', state = 'SP', address = 'Avenida Professor Francisco Morato - Butantã (SHOPPING BUTANTA)' WHERE id = 'store-336' OR code = 'SPO-336';
UPDATE public.stores SET cep = '01109-010', city = 'São Paulo', state = 'SP', address = 'Avenida Cruzeiro do Sul, 1100 - Canindé (SHOPPING DeD)' WHERE id = 'store-337' OR code = 'SPO-337';
UPDATE public.stores SET cep = '04523-900', city = 'São Paulo', state = 'SP', address = 'Avenida Ibirapuera, 3103 - Indianópolis (SHOPPING IBIRAPUERA)' WHERE id = 'store-338' OR code = 'SPO-338';
UPDATE public.stores SET cep = '15093-340', city = 'São José do Rio Preto', state = 'SP', address = 'Avenida Presidente Juscelino Kubitschek de Oliveira, 5000 - Iguatemi (SHOPPING IGUATEMI RIO PRETO)' WHERE id = 'store-339' OR code = 'SPO-339';
UPDATE public.stores SET cep = '04696-000', city = 'São Paulo', state = 'SP', address = 'Avenida Interlagos, 2255 - Jardim Interlagos (SHOPPING INTERLAGOS MM)' WHERE id = 'store-340' OR code = 'SPO-340';
UPDATE public.stores SET cep = '04153-000', city = 'São Paulo', state = 'SP', address = 'Praça Leonor Kaupa, 100 - Jardim da Saúde (SHOPPING PLAZA SUL)' WHERE id = 'store-341' OR code = 'SPO-341';
UPDATE public.stores SET cep = '09910-720', city = 'Diadema', state = 'SP', address = 'Rua Manoel da Nóbrega, 712 - Centro (SHOPPING PRACA DA MOCA)' WHERE id = 'store-342' OR code = 'SPO-342';
UPDATE public.stores SET cep = '14010-180', city = 'Ribeirão Preto', state = 'SP', address = 'Rua São José, 933 - Centro (SHOPPING SANTA URSULA)' WHERE id = 'store-343' OR code = 'SPO-343';
UPDATE public.stores SET cep = '08674-005', city = 'Suzano', state = 'SP', address = 'Rua Sete de Setembro, 555 - Parque Suzano (SHOPPING SUZANO)' WHERE id = 'store-344' OR code = 'SPO-344';
UPDATE public.stores SET cep = '06018-018', city = 'Osasco', state = 'SP', address = 'Avenida dos Autonomistas, 1400 - Vila Yara (SHOPPING UNIAO OSASCO)' WHERE id = 'store-345' OR code = 'SPO-345';
UPDATE public.stores SET cep = '06018-015', city = 'Osasco', state = 'SP', address = 'Avenida dos Autonomistas, 1765 - Vila Yara (SUPER SHOPPING OSASCO)' WHERE id = 'store-346' OR code = 'SPO-346';
UPDATE public.stores SET cep = '06763-040', city = 'Taboão da Serra', state = 'SP', address = 'Rodovia Régis Bittencourt, 2643 - Jardim Helena (SHOPPING TABOAO)' WHERE id = 'store-347' OR code = 'SPO-347';
UPDATE public.stores SET cep = '06460-000', city = 'Barueri', state = 'SP', address = 'Avenida Piracema, 669 - Tamboré (SHOPPING TAMBORE)' WHERE id = 'store-348' OR code = 'SPO-348';
UPDATE public.stores SET cep = '11680-000', city = 'Ubatuba', state = 'SP', address = 'Rua Doutor Esteves da Silva, 120 - Centro (UBATUBA MALL)' WHERE id = 'store-349' OR code = 'SPO-349';
UPDATE public.stores SET cep = '16016-500', city = 'Araçatuba', state = 'SP', address = 'Rua Carlos Pereira da Silva, 6001 - Guanabara (SHOPPING PRAÇA NOVA ARAÇATUBA)' WHERE id = 'store-350' OR code = 'SPO-350';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO CENTRAL PARK MM - São Paulo/SP' WHERE id = 'store-351' OR code = 'SPO-351';
UPDATE public.stores SET cep = '05577-200', city = 'São Paulo', state = 'SP', address = 'Rodovia Raposo Tavares, km 14,5 - Jardim Boa Vista (RAPOSO SHOPPING)' WHERE id = 'store-352' OR code = 'SPO-352';
UPDATE public.stores SET cep = '16901-005', city = 'Andradina', state = 'SP', address = 'Avenida Guanabara, 2919 - Vila Mineira (OESTE PLAZA ANDRADINA)' WHERE id = 'store-353' OR code = 'SPO-353';
UPDATE public.stores SET cep = '01016-040', city = 'São Paulo', state = 'SP', address = 'Largo Pátio do Colégio, 13 - Sé (LARGO 13)' WHERE id = 'store-354' OR code = 'SPO-354';
UPDATE public.stores SET cep = '72015-901', city = 'Brasília', state = 'DF', address = 'CSB 2 Lotes 1 a 4 - Taguatinga Sul (ALAMEDA SHOPPING)' WHERE id = 'store-355' OR code = 'SPO-355';
UPDATE public.stores SET cep = '47804-145', city = 'Barreiras', state = 'BA', address = 'Rua Aloísio Pereira do Vale - Cidade Nova (BARREIRAS RUA)' WHERE id = 'store-356' OR code = 'SPO-356';
UPDATE public.stores SET cep = '74063-010', city = 'Goiânia', state = 'GO', address = 'Rua 44, 399 - Setor Central (ARAGUAIA SHOPPING)' WHERE id = 'store-357' OR code = 'SPO-357';
UPDATE public.stores SET cep = '78050-970', city = 'Cuiabá', state = 'MT', address = 'Avenida Historiador Rubens de Mendonça, 3300 - Jardim Aclimação (PANTANAL SHOPPING MT)' WHERE id = 'store-358' OR code = 'SPO-358';
UPDATE public.stores SET cep = '78043-000', city = 'Cuiabá', state = 'MT', address = 'Avenida Miguel Sutil, 9300 - Santa Rosa (ESTACAO CUIABA)' WHERE id = 'store-359' OR code = 'SPO-359';
UPDATE public.stores SET cep = '74980-020', city = 'Aparecida de Goiânia', state = 'GO', address = 'Avenida Independência, Quadra Área Lote 01 - Setor Serra Dourada (APARECIDA SHOPPING)' WHERE id = 'store-360' OR code = 'SPO-360';
UPDATE public.stores SET cep = '74425-090', city = 'Goiânia', state = 'GO', address = 'Avenida Anhanguera, 10790 - Setor Aeroviário (SHOPPING CERRADO)' WHERE id = 'store-361' OR code = 'SPO-361';
UPDATE public.stores SET cep = '71615-560', city = 'Brasília', state = 'DF', address = 'Quadra SHIS QI 5 Bloco F Gilberto Salomão - Setor de Habitações Individuais Sul (GILBERTO SALOMAO)' WHERE id = 'store-362' OR code = 'SPO-362';
UPDATE public.stores SET cep = '70200-002', city = 'Brasília', state = 'DF', address = 'SCES Trecho 2 Lote 32 - Asa Sul (SHOPPING PIER 21)' WHERE id = 'store-363' OR code = 'SPO-363';
UPDATE public.stores SET cep = '78110-900', city = 'Cuiabá', state = 'MT', address = 'Avenida Governador João Ponce de Arruda, s/n - Jardim Aeroporto (Aeroporto Marechal Rondon)' WHERE id = 'store-364' OR code = 'SPO-364';
UPDATE public.stores SET cep = '01000-000', city = 'Brasília', state = 'DF', address = 'SPOLETO RUA SUDOESTE MM - Brasília/DF' WHERE id = 'store-365' OR code = 'SPO-365';
UPDATE public.stores SET cep = '01000-000', city = 'Brasília', state = 'DF', address = 'SPOLETO PICCOLO SAMAMBAIA MM - Brasília/DF' WHERE id = 'store-366' OR code = 'SPO-366';
UPDATE public.stores SET cep = '69912-440', city = 'Rio Branco', state = 'AC', address = 'Estrada da Floresta, 2320 - Floresta (VIA VERDE SHOPPING)' WHERE id = 'store-367' OR code = 'SPO-367';
UPDATE public.stores SET cep = '01000-000', city = 'Brasília', state = 'DF', address = 'SPOLETO COMPACTO POSTO 314 NORTE - Brasília/DF' WHERE id = 'store-368' OR code = 'SPO-368';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO ÁGUAS CLARAS SHOPPING - São Paulo/SP' WHERE id = 'store-369' OR code = 'SPO-369';
UPDATE public.stores SET cep = '74150-340', city = 'Goiânia', state = 'GO', address = 'Avenida Mutirão - Setor Marista (ORION)' WHERE id = 'store-370' OR code = 'SPO-370';
UPDATE public.stores SET cep = '01000-000', city = 'Brasília', state = 'DF', address = 'SPOLETO CNB SHOPPING - Brasília/DF' WHERE id = 'store-371' OR code = 'SPO-371';
UPDATE public.stores SET cep = '74230-030', city = 'Goiânia', state = 'GO', address = 'Avenida T-10, 1300 - Setor Bueno (GOIANIA SHOPPING)' WHERE id = 'store-372' OR code = 'SPO-372';
UPDATE public.stores SET cep = '01000-000', city = 'Brasília', state = 'DF', address = 'SPOLETO GUARÁ MM - Brasília/DF' WHERE id = 'store-373' OR code = 'SPO-373';
UPDATE public.stores SET cep = '72876-900', city = 'Valparaíso de Goiás', state = 'GO', address = 'Rodovia BR-040, km 12 - Parque Esplanada III (SHOPPING SUL)' WHERE id = 'store-374' OR code = 'SPO-374';
UPDATE public.stores SET cep = '01000-000', city = 'São Paulo', state = 'SP', address = 'SPOLETO DARK KITCHEN ALTANA MM - São Paulo/SP' WHERE id = 'store-375' OR code = 'SPO-375';
UPDATE public.stores SET cep = '01000-000', city = 'Brasília', state = 'DF', address = 'SPOLETO QUE GAMA MM - Brasília/DF' WHERE id = 'store-376' OR code = 'SPO-376';
UPDATE public.stores SET cep = '70632-400', city = 'Brasília', state = 'DF', address = 'STN Conjunto J - Asa Norte (SHOPPING BOULEVARD BRASILIA)' WHERE id = 'store-377' OR code = 'SPO-377';
UPDATE public.stores SET cep = '71680-362', city = 'Brasília', state = 'DF', address = 'Condomínio San Diego, LOTES 24/25 - Setor Habitacional Jardim Botânico (JARDIM BOTANICO DF)' WHERE id = 'store-378' OR code = 'SPO-378';
UPDATE public.stores SET cep = '36080-001', city = 'Juiz de Fora', state = 'MG', address = 'Avenida Brasil, 6345 - Mariano Procópio (SHOPPING JARDIM NORTE)' WHERE id = 'store-379' OR code = 'SPO-379';
UPDATE public.stores SET cep = '38180-570', city = 'Araxá', state = 'MG', address = 'Rua Abílio Cassimiro de Araújo - Residencial Camuá (ARAXÁ)' WHERE id = 'store-380' OR code = 'SPO-380';
UPDATE public.stores SET cep = '30320-900', city = 'Belo Horizonte', state = 'MG', address = 'Rodovia BR-356, 3049 - Belvedere (BH SHOPPING)' WHERE id = 'store-381' OR code = 'SPO-381';
UPDATE public.stores SET cep = '30260-070', city = 'Belo Horizonte', state = 'MG', address = 'Avenida dos Andradas, 3000 - Santa Efigênia (SHOPPING BOULEVARD BH)' WHERE id = 'store-382' OR code = 'SPO-382';
UPDATE public.stores SET cep = '30160-040', city = 'Belo Horizonte', state = 'MG', address = 'Rua Rio de Janeiro - Centro (CENTRO BH)' WHERE id = 'store-383' OR code = 'SPO-383';
UPDATE public.stores SET cep = '30180-111', city = 'Belo Horizonte', state = 'MG', address = 'Avenida Olegário Maciel, 1600 - Lourdes (SHOPPING DIAMOND MALL)' WHERE id = 'store-384' OR code = 'SPO-384';
UPDATE public.stores SET cep = '01000-000', city = 'Belo Horizonte', state = 'MG', address = 'SPOLETO GUTIERREZ MM  --> PRADO - Belo Horizonte/MG' WHERE id = 'store-385' OR code = 'SPO-385';
UPDATE public.stores SET cep = '35010-252', city = 'Governador Valadares', state = 'MG', address = 'Rua Sete de Setembro, 3500 - Centro (GV SHOPPING)' WHERE id = 'store-386' OR code = 'SPO-386';
UPDATE public.stores SET cep = '32210-110', city = 'Contagem', state = 'MG', address = 'Avenida General David Sarnoff, 5160 - Cidade Industrial (ITAU POWER SHOPPING)' WHERE id = 'store-387' OR code = 'SPO-387';
UPDATE public.stores SET cep = '32655-505', city = 'Betim', state = 'MG', address = 'Rodovia Fernão Dias, km 492 - São João (METROPOLITAN SHOPPING BETIM)' WHERE id = 'store-388' OR code = 'SPO-388';
UPDATE public.stores SET cep = '31160-430', city = 'Belo Horizonte', state = 'MG', address = 'Avenida Cristiano Machado, 4000 - União (MINAS SHOPPING)' WHERE id = 'store-389' OR code = 'SPO-389';
UPDATE public.stores SET cep = '35500-011', city = 'Divinópolis', state = 'MG', address = 'Rua Moacir José Leite, 100 - Santa Clara (PATIO DIVINOPOLIS)' WHERE id = 'store-390' OR code = 'SPO-390';
UPDATE public.stores SET cep = '30110-028', city = 'Belo Horizonte', state = 'MG', address = 'Praça Rio Branco, 100 - Centro (RODOVIARIA BH)' WHERE id = 'store-391' OR code = 'SPO-391';
UPDATE public.stores SET cep = '01000-000', city = 'Belo Horizonte', state = 'MG', address = 'SPOLETO RUA SAVASSI MM - Belo Horizonte/MG' WHERE id = 'store-392' OR code = 'SPO-392';
UPDATE public.stores SET cep = '35702-353', city = 'Sete Lagoas', state = 'MG', address = 'Avenida Otávio Campelo Ribeiro, 2801 - Eldorado (SHOPPING SETE LAGOAS)' WHERE id = 'store-393' OR code = 'SPO-393';
UPDATE public.stores SET cep = '01405-000', city = 'São Paulo', state = 'SP', address = 'Rua Pamplona - Jardim Paulista (SHOPPING CIDADE)' WHERE id = 'store-394' OR code = 'SPO-394';
UPDATE public.stores SET cep = '32115-000', city = 'Contagem', state = 'MG', address = 'Avenida Severino Ballesteros Rodrigues, 850 - Cabral (SHOPPING CONTAGEM)' WHERE id = 'store-395' OR code = 'SPO-395';
UPDATE public.stores SET cep = '31250-010', city = 'Belo Horizonte', state = 'MG', address = 'Avenida Presidente Carlos Luz, 3001 - Caiçara (SHOPPING DEL REY)' WHERE id = 'store-396' OR code = 'SPO-396';
UPDATE public.stores SET cep = '31710-580', city = 'Belo Horizonte', state = 'MG', address = 'Avenida Cristiano Machado, 11833 - Vila Clóris (SHOPPING ESTACAO BH)' WHERE id = 'store-397' OR code = 'SPO-397';
UPDATE public.stores SET cep = '35160-281', city = 'Ipatinga', state = 'MG', address = 'Avenida Pedro Linhares Gomes, 3900 - Industrial (SHOPPING IPATINGA)' WHERE id = 'store-398' OR code = 'SPO-398';
UPDATE public.stores SET cep = '39400-547', city = 'Montes Claros', state = 'MG', address = 'Avenida Donato Quintino, 90 - Caniçares (SHOPPING MONTES CLAROS)' WHERE id = 'store-399' OR code = 'SPO-399';
UPDATE public.stores SET cep = '37026-440', city = 'Varginha', state = 'MG', address = 'Rua Humberto Pizzo, 999 - Jardim Canaã (SHOPPING VIA CAFÉ GARDEM)' WHERE id = 'store-400' OR code = 'SPO-400';
UPDATE public.stores SET cep = '30640-070', city = 'Belo Horizonte', state = 'MG', address = 'Avenida Afonso Vaz de Melo, 640 - Barreiro (VIA SHOPPING BARREIRO)' WHERE id = 'store-401' OR code = 'SPO-401';
UPDATE public.stores SET cep = '01000-000', city = 'Betim', state = 'MG', address = 'SPOLETO BETIM MM - Betim/MG' WHERE id = 'store-402' OR code = 'SPO-402';
UPDATE public.stores SET cep = '30112-010', city = 'Belo Horizonte', state = 'MG', address = 'Avenida do Contorno, 6061 - São Pedro (PATIO SAVASSI)' WHERE id = 'store-403' OR code = 'SPO-403';
UPDATE public.stores SET cep = '32210-110', city = 'Contagem', state = 'MG', address = 'Avenida Babita Camargos, 1295 - Cidade Industrial (OUTLET SÓ MARCAS MM)' WHERE id = 'store-404' OR code = 'SPO-404';
UPDATE public.stores SET cep = '01000-000', city = 'São João del-Rei', state = 'MG', address = 'SPOLETO PATIO MATOSINHO PICCOLO - São João del-Rei/MG' WHERE id = 'store-405' OR code = 'SPO-405';
UPDATE public.stores SET cep = '33500-000', city = 'Confins', state = 'MG', address = 'Rodovia LMG-800, km 7,9 - Confins (AEROPORTO CONFINS)' WHERE id = 'store-406' OR code = 'SPO-406';
UPDATE public.stores SET cep = '01000-000', city = 'Belo Horizonte', state = 'MG', address = 'SPOLETO BOULEVARD COLINA - Belo Horizonte/MG' WHERE id = 'store-407' OR code = 'SPO-407';
UPDATE public.stores SET cep = '35065-142', city = 'Governador Valadares', state = 'MG', address = 'Rua José Ivair Ferreira Mattos - Lagoa Santa (LAGOA SANTA)' WHERE id = 'store-408' OR code = 'SPO-408';
UPDATE public.stores SET cep = '37202-776', city = 'Lavras', state = 'MG', address = 'Rua Gil Júlio de Souza - Jardim América (LAVRAS)' WHERE id = 'store-409' OR code = 'SPO-409';
