import { INITIAL_STORES } from '../src/data/initialData.js';

const rawData = `
SPOLETO MAG SHOPPING	ALEX DE BRISTO
SPOLETO MANAIRA SHOPPING (reforma)	ALEX DE BRISTO
SPOLETO MANGABEIRA SHOPPING	ALEX DE BRISTO
SPOLETO PARTAGE SHOPPING CAMPINA GRANDE	ALEX DE BRISTO
SPOLETO EPITACIO MM	ALEX DE BRISTO
SPOLETO AEROPORTO RECIFE MM	ALEX DE BRISTO
SPOLETO PLAZA CASA FORTE	ALEX DE BRISTO
SPOLETO SHOPPING RECIFE	ALEX DE BRISTO
SPOLETO SHOPPING RIOMAR RECIFE	ALEX DE BRISTO
SPOLETO SHOPPING TACARUNA	ALEX DE BRISTO
SPOLETO PATOS SHOPPING	ALEX DE BRISTO
SPOLETO JUA GARDEN	ALEX DE BRISTO
SPOLETO AEROPORTO MACEIO	ALEX DE BRISTO
SPOLETO JATIUCA MM	ALEX DE BRISTO
SPOLETO GRUTA MM	ALEX DE BRISTO
SPOLETO PARQUE SHOPPING MACEIO	ALEX DE BRISTO
SPOLETO PARQUE SHOPPING BAHIA	ALEX DE BRISTO
SPOLETO SALVADOR SHOPPING	ALEX DE BRISTO
SPOLETO SHOPPING BARRA	ALEX DE BRISTO
SPOLETO SHOPPING DA BAHIA	ALEX DE BRISTO
SPOLETO SHOPPING PARALELA	ALEX DE BRISTO
SPOLETO MIDWAY SHOPPING (ficou fechada)	ALEX DE BRISTO
SPOLETO BAURU SHOPPING	ALEXANDRE DE PAULA
SPOLETO BOULEVARD BAURU SHOPPING	ALEXANDRE DE PAULA
SPOLETO EL DOURADO EVENTOS	ALEXANDRE DE PAULA
SPOLETO MAXI SHOPPING JUNDIAI	ALEXANDRE DE PAULA
SPOLETO PLAZA SHOPPING ITU	ALEXANDRE DE PAULA
SPOLETO POLO SHOPPING INDAIATUBA	ALEXANDRE DE PAULA
SPOLETO BOULEVARD MOGI GUAÇU	ALEXANDRE DE PAULA
SPOLETO CENTER VALE SHOPPING	ALEXANDRE DE PAULA
SPOLETO SHOPPING COLINAS	ALEXANDRE DE PAULA
SPOLETO IGUATEMI SAO CARLOS	ALEXANDRE DE PAULA
SPOLETO JACAREI SHOPPING	ALEXANDRE DE PAULA
SPOLETO JARAGUA ARARAQUARA	ALEXANDRE DE PAULA
SPOLETO JUNDIAI SHOPPING	ALEXANDRE DE PAULA
SPOLETO SHOPPING RIO CLARO	ALEXANDRE DE PAULA
SPOLETO SHOPPING SP MARKET	ALEXANDRE DE PAULA
SPOLETO TAUBATE SHOPPING	ALEXANDRE DE PAULA
SPOLETO VALE SUL SHOPPING	ALEXANDRE DE PAULA
SPOLETO SHOPPING VALINHOS	ALEXANDRE DE PAULA
SPOLETO SOROCABA MM	ALEXANDRE DE PAULA
SPOLETO AEROPORTO GUARULHOS T2	ALEXANDRE DE PAULA
SPOLETO SHOPPING IGUATEMI ESPLANADA	ALEXANDRE DE PAULA
SPOLETO SHOPPING CIDADE SOROCABA	ALEXANDRE DE PAULA
SPOLETO VIA VALE GARDEN SHOPPING	ALEXANDRE DE PAULA
SPOLETO OUTLET CATARINA FASHION	ALEXANDRE DE PAULA
SPOLETO VINHEDO OPEN MALL	ALEXANDRE DE PAULA
SPOLETO SHOPPING BONSUCESSO	ALEXANDRE DE PAULA
SPOLETO SERRA SUL MM	ALEXANDRE DE PAULA
SPOLETO PARTAGE POÇOS DE CALDAS	ALEXANDRE DE PAULA
SPOLETO CANTAREIRA NORTE SHOPPING	ALEXANDRE DE PAULA
SPOLETO SHOPPING BURITI MOGI GUACU	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING BRAGANCA GARDEN	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO AEROPORTO VIRACOPOS	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO PARQUE SHOPPING BARUERI	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING TOP CENTER	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO GRAND PLAZA SHOPPING	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO PAMPLONA SHOPPING	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO PARK SHOPPING SAO CAETANO	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING JARDIM SUL	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING METRO TATUAPE	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING METRO TUCURUVI	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO PARQUE DAS BANDEIRAS	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING VILA OLIMPIA	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING VILLA LOBOS MM	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO TIETE PLAZA SHOPPING	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING ANHANGUERA CAJAMAR	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING PARKCITY SUMARÉ	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING GALLERIA CAMPINAS	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING MARKET PLACE	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO PARQUE DA CIDADE	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING IGUATEMI ALPHAVILLE	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO MORUMBI TOWN	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING HIGIENOPOLIS	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO CAMPINAS SHOPPING	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING LIGHT	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING JK IGUATEMI	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING BOULEVARD TATUAPE	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO SHOPPING MORUMBI	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO HORTOLÂNDIA	CHRISTIANE RAMOS PEREIRA DE SOUZA
SPOLETO ROSARIO MM	CINTHIA MILLIOLE
SPOLETO RESENDE SHOPPING	CINTHIA MILLIOLE
SPOLETO SHOPPING METROPOLITANO	CINTHIA MILLIOLE
SPOLETO SHOPPING PARK SUL VR	CINTHIA MILLIOLE
SPOLETO VOLTA REDONDA MM	CINTHIA MILLIOLE
SPOLETO AEROPORTO TOM JOBIM	CINTHIA MILLIOLE
SPOLETO TAQUARA PLAZA	CINTHIA MILLIOLE
SPOLETO OUTLET WASHINGTON LUIZ MM	CINTHIA MILLIOLE
SPOLETO RUA BUENOS AIRES	CINTHIA MILLIOLE
SPOLETO SHOPPING AMERICAS	CINTHIA MILLIOLE
SPOLETO TERMINAL RODOVIARIO NOVO RIO	CINTHIA MILLIOLE
SPOLETO PICCOLO GUANABARA RECREI	CINTHIA MILLIOLE
SPOLETO RUA RB1	CINTHIA MILLIOLE
SPOLETO CARIOCA SHOPPING	CINTHIA MILLIOLE
SPOLETO SHOPPING GAVEA	CINTHIA MILLIOLE
SPOLETO NOVA IGUACU RUA MM	CINTHIA MILLIOLE
SPOLETO CAXIAS SHOPPING 2 MM	CINTHIA MILLIOLE
SPOLETO RUA MARIZ E BARROS	CINTHIA MILLIOLE
SPOLETO SHOPPING NOVA IGUACU	CINTHIA MILLIOLE
SPOLETO TOP SHOPPING MM	CINTHIA MILLIOLE
SPOLETO SHOPPING JACAREPAGUA	CINTHIA MILLIOLE
SPOLETO SHOPPING VOLTA REDONDA	CINTHIA MILLIOLE
SPOLETO BONSUCESSO RUA MM	CINTHIA MILLIOLE
SPOLETO CAXIAS RUA	CINTHIA MILLIOLE
SPOLETO ILHA PLAZA SHOPPING	CINTHIA MILLIOLE
SPOLETO SHOPPING SULACAP	CINTHIA MILLIOLE
SPOLETO CASA SHOPPING	CINTHIA MILLIOLE
SPOLETO JARDIM GUADALUPE 2	CINTHIA MILLIOLE
SPOLETO SHOPPING NOVO LEBLON	CINTHIA MILLIOLE
SPOLETO GUANABARA BARRA	CINTHIA MILLIOLE
SPOLETO ARCOVERDE	CINTHIA MILLIOLE
SPOLETO CATARATAS JL SHOPPING	EDUARDO SPISLA
SPOLETO ATLANTICO	EDUARDO SPISLA
SPOLETO AURORA SHOPPING LONDRINA	EDUARDO SPISLA
SPOLETO BLUMENAU	EDUARDO SPISLA
SPOLETO CONTINENTE PARK SHOPPING	EDUARDO SPISLA
SPOLETO FLORIPA SHOPPING	EDUARDO SPISLA
SPOLETO ITAJAÍ MM	EDUARDO SPISLA
SPOLETO J L SHOPPING CASCAVEL	EDUARDO SPISLA
SPOLETO SHOPPING BEIRA MAR	EDUARDO SPISLA
SPOLETO SHOPPING CATUAÍ MARINGÁ	EDUARDO SPISLA
SPOLETO SHOPPING CIDADE DOS LAGOS	EDUARDO SPISLA
SPOLETO SHOPPING IGUATEMI PORTO ALEGRE	EDUARDO SPISLA
SPOLETO SHOPPING MARINGA	EDUARDO SPISLA
SPOLETO SHOPPING PATIO CHAPECO	EDUARDO SPISLA
SPOLETO UMUARAMA	EDUARDO SPISLA
SPOLETO BOURBON SHOPPING IPIRANGA	EDUARDO SPISLA
SPOLETO CATUAÍ CASCAVEL	EDUARDO SPISLA
SPOLETO PARK SHOPPING CANOAS	EDUARDO SPISLA
SPOLETO PB SHOPPING PATO BRANCO	EDUARDO SPISLA
SPOLETO SHOPPING NOVO HAMBURGO	EDUARDO SPISLA
SPOLETO SHOPPING CAMPO MOURÃO	EDUARDO SPISLA
SPOLETO SHOPPING MUELLER	EDUARDO SPISLA
SPOLETO PARK SHOPPING BARIGUI	EDUARDO SPISLA
SPOLETO SHOPPING ESTAÇÃO CURITIBA	EDUARDO SPISLA
SPOLETO PALLADIUM CURITIBA	EDUARDO SPISLA
SPOLETO JOINVILLE MM (DELIVERY)	EDUARDO SPISLA
SPOLETO VILLA ROMANA	EDUARDO SPISLA
SPOLETO CAMPO GERAIS PONTA GROSSA	EDUARDO SPISLA
SPOLETO SHOPPING FREI CANECA	FABIO FAUSTINO DO CARMO
SPOLETO SHOPPING D	FABIO FAUSTINO DO CARMO
SPOLETO LIMEIRA	FABIO FAUSTINO DO CARMO
SPOLETO AMERICANA	FABIO FAUSTINO DO CARMO
SPOLETO SHOPPING BOAVISTA	FABIO FAUSTINO DO CARMO
SPOLETO TRIMAIS PLACES	FABIO FAUSTINO DO CARMO
SPOLETO SHOPPING DOM PEDRO	FABIO FAUSTINO DO CARMO
SPOLETO CARREFOUR MARGINAL PINHEIROS	FABIO FAUSTINO DO CARMO
SPOLETO SHOPPING GRANJA VIANNA	FABIO FAUSTINO DO CARMO
SPOLETO POSTO LAGO AZUL	FABIO FAUSTINO DO CARMO
SPOLETO EXTRA ANHANGUERA	FABIO FAUSTINO DO CARMO
SPOLETO OUTLET PREMIUM ITUPEVA	FABIO FAUSTINO DO CARMO
SPOLETO CAMPO GRANDE MS	FABRÍCIO GUEDES
SPOLETO NORTE SUL PLAZA	FABRÍCIO GUEDES
SPOLETO TAGUATINGA PISTAO SUL	FABRÍCIO GUEDES
SPOLETO ÁGUAS LINDAS SHOPPING PICCOLO	FABRÍCIO GUEDES
SPOLETO SHOPPING CEILANDIA	FABRÍCIO GUEDES
SPOLETO SHOPPING BOSQUE DOS IPES	FABRÍCIO GUEDES
SPOLETO SHOPPING CAMPO GRANDE	FABRÍCIO GUEDES
SPOLETO SINOP MT MM	FABRÍCIO GUEDES
SPOLETO VILA SÃO TOMAZ	FABRÍCIO GUEDES
SPOLETO PASSEIO DAS AGUAS SHOPPING	FABRÍCIO GUEDES
SPOLETO BUENA VISTA	FABRÍCIO GUEDES
SPOLETO SHOPPING IGUATEMI DF	FABRÍCIO GUEDES
SPOLETO PARK SHOPPING DF	FABRÍCIO GUEDES
SPOLETO PALMAS SHOPPING	FABRÍCIO GUEDES
SPOLETO 307 SUL	FABRÍCIO GUEDES
SPOLETO SHOPPING BOUGAINVILLE	FABRÍCIO GUEDES
SPOLETO BRASILIA SHOPPING	FABRÍCIO GUEDES
SPOLETO FLAMBOYANT SHOPPING	FABRÍCIO GUEDES
SPOLETO AGUAS CLARAS MM	FABRÍCIO GUEDES
SPOLETO TAGUATINGA SHOPPING	FABRÍCIO GUEDES
SPOLETO TERRACO SHOPPING	FABRÍCIO GUEDES
SPOLETO PATIO BRASIL SHOPPING	FABRÍCIO GUEDES
SPOLETO SHOPPING DF PLAZA	FABRÍCIO GUEDES
SPOLETO NOROESTE MM	FABRÍCIO GUEDES
SPOLETO BARRA SHOPPING	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING DOWNTOWN	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING TIJUCA	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO PARK JACAREPAGUA	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING VIA PARQUE	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO RUA LARGO DO MACHADO	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO MADUREIRA SHOPPING	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO COPACABANA MM	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO BOULEVARD SHOPPING VILA VELHA	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO CACHOEIRO	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO MASTER PLACE MALL	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING MESTRE ALVARO	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING MONTSERRAT	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING MOXUARA	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING PRAIA DA COSTA	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING VILA VELHA MM	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING VITORIA	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO RECREIO SHOPPING	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO BARRA SHOPPING 2	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING GRANDE RIO	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING IGUATEMI RIO	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO PARK SHOPPING CAMPO GRANDE	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO WEST SHOPPING	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO ALDEIA DA SERRA MM	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO BANGU SHOPPING	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING BARRA SQUARE	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO RUA ICARAI	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO RUA TIJUCA MM	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO SHOPPING VIA BRASIL PICCOLO	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO RUA ENSEADA	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO RUA CRUZ VERMELHA	ISRAEL LOMARDES ROCHA DA SILVA
SPOLETO AEROPORTO SALVADOR	KATARINY GOULART
SPOLETO SHOPPING BELA VISTA	KATARINY GOULART
SPOLETO PICCOLO MARACANAÚ MM	KATARINY GOULART
SPOLETO CARIRI SHOPPING	KATARINY GOULART
SPOLETO NORTH SHOPPING SOBRAL II	KATARINY GOULART
SPOLETO BOULEVARD VITORIA DA CONQUISTA	KATARINY GOULART
SPOLETO COMPACTO SHOPPING VIA SUL	KATARINY GOULART
SPOLETO RIOMAR KENNEDY	KATARINY GOULART
SPOLETO SHOPPING RIOMAR FORTALEZA MM	KATARINY GOULART
SPOLETO SHOPPING BENFICA	KATARINY GOULART
SPOLETO SHOPPING IGUATEMI FORTALEZA	KATARINY GOULART
SPOLETO SHOPPING DEL PASEO	KATARINY GOULART
SPOLETO TERRAZO SHOPPING	KATARINY GOULART
SPOLETO SHOPPING PARANGABA	KATARINY GOULART
SPOLETO JEQUITIBA PLAZA SHOPPING	KATARINY GOULART
SPOLETO SHOPPING CONQUISTA SUL	KATARINY GOULART
SPOLETO PICCOLO RODOVIARIA SALVADOR	KATARINY GOULART
SPOLETO SHOPPING FEIRA DE SANTANA	KATARINY GOULART
SPOLETO SHOPPING IGUATEMI CAMPINAS	MARCELO CORA SILVA DIAS
SPOLETO SHOPPING PAULISTA	MARCELO CORA SILVA DIAS
SPOLETO SHOPPING CIDADE SAO PAULO	MARCELO CORA SILVA DIAS
SPOLETO SHOPPING ELDORADO	MARCELO CORA SILVA DIAS
SPOLETO SHOPPING BOSQUE MAIA	MARCELO CORA SILVA DIAS
SPOLETO SHOPPING GUARULHOS	MARCELO CORA SILVA DIAS
SPOLETO SHOPPING WEST PLAZA	MARCELO CORA SILVA DIAS
SPOLETO SHOPPING CENTER 3	MARCELO CORA SILVA DIAS
SPOLETO BOURBON SHOPPING	MARCELO CORA SILVA DIAS
SPOLETO SHOPPING METRO SANTA CRUZ	MARCELO CORA SILVA DIAS
SPOLETO COMPACTO CARREFOUR LIMAO	MARCELO CORA SILVA DIAS
SPOLETO PARQUE PRADO SP PICCOLO	MARCELO CORA SILVA DIAS
SPOLETO SHOPPING PIRACICABA	MARCELO CORA SILVA DIAS
SPOLETO EVENTOS - RIO	MAYARA MOREIRA DAMASCO
SPOLETO RUA MEXICO	MAYARA MOREIRA DAMASCO
SPOLETO FOOD TRUCK TERESOPOLIS	MAYARA MOREIRA DAMASCO
SPOLETO BOULEVARD SAO GONCALO	MAYARA MOREIRA DAMASCO
SPOLETO PLAZA SHOPPING NITEROI	MAYARA MOREIRA DAMASCO
SPOLETO RUA LEBLON	MAYARA MOREIRA DAMASCO
SPOLETO RUA PETROPOLIS	MAYARA MOREIRA DAMASCO
SPOLETO POSTO MARICA	MAYARA MOREIRA DAMASCO
SPOLETO SAO GONCALO SHOPPING	MAYARA MOREIRA DAMASCO
SPOLETO SHOPPING BAY MARKET	MAYARA MOREIRA DAMASCO
SPOLETO SHOPPING LEBLON	MAYARA MOREIRA DAMASCO
SPOLETO SHOPPING NOVA AMERICA	MAYARA MOREIRA DAMASCO
SPOLETO SHOPPING NOVA AMERICA II MM	MAYARA MOREIRA DAMASCO
SPOLETO SHOPPING PÁTIO ALCÂNTARA	MAYARA MOREIRA DAMASCO
SPOLETO SHOPPING RIO SUL	MAYARA MOREIRA DAMASCO
SPOLETO FRIBURGO SHOPPING	MAYARA MOREIRA DAMASCO
SPOLETO NORTE SHOPPING	MAYARA MOREIRA DAMASCO
SPOLETO TERESOPOLIS SHOPPING	MAYARA MOREIRA DAMASCO
SPOLETO BOULEVARD CAMPOS	MAYARA MOREIRA DAMASCO
SPOLETO RUA MACAE CAVALEIROS	MAYARA MOREIRA DAMASCO
SPOLETO SHOPPING PARK LAGOS	MAYARA MOREIRA DAMASCO
SPOLETO SHOPPING PLAZA MACAE	MAYARA MOREIRA DAMASCO
SPOLETO SHOPPING RIO DAS OSTRAS	MAYARA MOREIRA DAMASCO
SPOLETO PENINSULA MALL	MAYARA MOREIRA DAMASCO
SPOLETO BOSSA NOVA MALL	MAYARA MOREIRA DAMASCO
SPOLETO BOTAFOGO PRAIA SHOPPING	MAYARA MOREIRA DAMASCO
SPOLETO RUA COPACABANA II	MAYARA MOREIRA DAMASCO
SPOLETO COMPACTO ITAIPU MULTICENTER	MAYARA MOREIRA DAMASCO
SPOLETO BOTAFOGO RUA MM	MAYARA MOREIRA DAMASCO
SPOLETO SHOPPING DO MEIER	MAYARA MOREIRA DAMASCO
SPOLETO ARRAIAL DO CABO PICCOLO	MAYARA MOREIRA DAMASCO
SPOLETO INDEPENDENCIA SHOPPING	MAYARA MOREIRA DAMASCO
SPOLETO AMAZONAS SHOPPING	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO BOA VISTA RUA	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO BOULEVARD SHOPPING BELEM	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO CASTANHEIRAS SHOPPING	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO MACAPA SHOPPING	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO PARK SUMAUMA	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO PARQUE SHOPPING BELEM	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO RUA NAZARE MM	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO SHOPPING GRAO PARA	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO SHOPPING PATIO BELEM	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO MANAUARA SHOPPING	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO PONTA NEGRA	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO SHOPPING ANANINDEUA	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO SHOPPING DA ILHA	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO SÃO LUIS SHOPPING	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO VIA NORTE	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO MANAUS PLAZA	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO SHOPPING RIO POTY	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO TERESINA SHOPPING	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO PORTO VELHO SHOPPING	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO PORTO VELHO DK	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO DK PORTO VELHO	PABLO HENRIQUE FERREIRA SIMPLICIO
SPOLETO JABAQUARA PICCOLO MM	PERCY PINHEIRO
SPOLETO GOLDEN SQUARE SHOPPING	PERCY PINHEIRO
SPOLETO ATRIUM SHOPPING SANTO ANDRE	PERCY PINHEIRO
SPOLETO SHOPPING ABC	PERCY PINHEIRO
SPOLETO GUARUJÁ	PERCY PINHEIRO
SPOLETO SAO BERNARDO PLAZA SHOPPING	PERCY PINHEIRO
SPOLETO BRISAMAR SHOPPING	PERCY PINHEIRO
SPOLETO CENTRAL PLAZA SHOPPING	PERCY PINHEIRO
SPOLETO OUTLET PREMIUM GRANDE SP	PERCY PINHEIRO
SPOLETO MAUA PLAZA SHOPPING	PERCY PINHEIRO
SPOLETO PATTEO URUPEMA	PERCY PINHEIRO
SPOLETO LITORAL PLAZA SHOPPING	PERCY PINHEIRO
SPOLETO POSTO ARCO IRIS	PERCY PINHEIRO
SPOLETO SHOPPING METRO ITAQUERA	PERCY PINHEIRO
SPOLETO PRAIAMAR SHOPPING	PERCY PINHEIRO
SPOLETO SANTANA PARQUE SHOPPING MM	PERCY PINHEIRO
SPOLETO SANTOS RUA	PERCY PINHEIRO
SPOLETO SHOPPING ANALIA FRANCO	PERCY PINHEIRO
SPOLETO SHOPPING ARICANDUVA	PERCY PINHEIRO
SPOLETO SHOPPING BURITI GUARA	PERCY PINHEIRO
SPOLETO SHOPPING CENTER NORTE	PERCY PINHEIRO
SPOLETO SHOPPING LED BARRA FUNDA	PERCY PINHEIRO
SPOLETO SHOPPING METROPOLE	PERCY PINHEIRO
SPOLETO MOOCA PLAZA SHOPPING	PERCY PINHEIRO
SPOLETO SHOPPING PARQUE BALNEARIO	PERCY PINHEIRO
SPOLETO SHOPPING PATIO PINDA	PERCY PINHEIRO
SPOLETO SHOPPING ALEGRIA	PERCY PINHEIRO
SPOLETO PICCOLO HIPER ANDORINHA	PERCY PINHEIRO
SPOLETO CARREFOUR ARICANDUVA	PERCY PINHEIRO
SPOLETO FRANCA	RENE SANTOS DO VALE
SPOLETO IGUATEMI RIBEIRAO PRETO	RENE SANTOS DO VALE
SPOLETO MOGI SHOPPING	RENE SANTOS DO VALE
SPOLETO NOVO SHOPPING	RENE SANTOS DO VALE
SPOLETO OPEN SQUARE	RENE SANTOS DO VALE
SPOLETO OSASCO PLAZA SHOPPING	RENE SANTOS DO VALE
SPOLETO CONTINENTAL SHOPPING	RENE SANTOS DO VALE
SPOLETO PENHA SHOPPING	RENE SANTOS DO VALE
SPOLETO RIBEIRAO SHOPPING	RENE SANTOS DO VALE
SPOLETO SERRAMAR PARQUE SHOPPING	RENE SANTOS DO VALE
SPOLETO SHOPPING BUTANTA	RENE SANTOS DO VALE
SPOLETO SHOPPING DeD	RENE SANTOS DO VALE
SPOLETO SHOPPING IBIRAPUERA	RENE SANTOS DO VALE
SPOLETO SHOPPING IGUATEMI RIO PRETO	RENE SANTOS DO VALE
SPOLETO SHOPPING INTERLAGOS MM	RENE SANTOS DO VALE
SPOLETO SHOPPING PLAZA SUL	RENE SANTOS DO VALE
SPOLETO SHOPPING PRACA DA MOCA	RENE SANTOS DO VALE
SPOLETO SHOPPING SANTA URSULA	RENE SANTOS DO VALE
SPOLETO SHOPPING SUZANO	RENE SANTOS DO VALE
SPOLETO SHOPPING UNIAO OSASCO	RENE SANTOS DO VALE
SPOLETO SUPER SHOPPING OSASCO	RENE SANTOS DO VALE
SPOLETO SHOPPING TABOAO	RENE SANTOS DO VALE
SPOLETO SHOPPING TAMBORE	RENE SANTOS DO VALE
SPOLETO UBATUBA MALL	RENE SANTOS DO VALE
SPOLETO SHOPPING PRAÇA NOVA ARAÇATUBA	RENE SANTOS DO VALE
SPOLETO CENTRAL PARK MM	RENE SANTOS DO VALE
SPOLETO RAPOSO SHOPPING	RENE SANTOS DO VALE
SPOLETO OESTE PLAZA ANDRADINA	RENE SANTOS DO VALE
SPOLETO LARGO 13	RENE SANTOS DO VALE
SPOLETO ALAMEDA SHOPPING	ROSA ALICE GUEDES DE SOUZA
SPOLETO BARREIRAS RUA	ROSA ALICE GUEDES DE SOUZA
SPOLETO ARAGUAIA SHOPPING	ROSA ALICE GUEDES DE SOUZA
SPOLETO PANTANAL SHOPPING MT	ROSA ALICE GUEDES DE SOUZA
SPOLETO ESTACAO CUIABA	ROSA ALICE GUEDES DE SOUZA
SPOLETO APARECIDA SHOPPING	ROSA ALICE GUEDES DE SOUZA
SPOLETO SHOPPING CERRADO	ROSA ALICE GUEDES DE SOUZA
SPOLETO GILBERTO SALOMAO	ROSA ALICE GUEDES DE SOUZA
SPOLETO SHOPPING PIER 21	ROSA ALICE GUEDES DE SOUZA
SPOLETO AEROPORTO CUIABA	ROSA ALICE GUEDES DE SOUZA
SPOLETO RUA SUDOESTE MM	ROSA ALICE GUEDES DE SOUZA
SPOLETO PICCOLO SAMAMBAIA MM	ROSA ALICE GUEDES DE SOUZA
SPOLETO RIO BRANCO	ROSA ALICE GUEDES DE SOUZA
SPOLETO VIA VERDE SHOPPING	ROSA ALICE GUEDES DE SOUZA
SPOLETO COMPACTO POSTO 314 NORTE	ROSA ALICE GUEDES DE SOUZA
SPOLETO ÁGUAS CLARAS SHOPPING	ROSA ALICE GUEDES DE SOUZA
SPOLETO ORION	ROSA ALICE GUEDES DE SOUZA
SPOLETO CNB SHOPPING	ROSA ALICE GUEDES DE SOUZA
SPOLETO GOIANIA SHOPPING	ROSA ALICE GUEDES DE SOUZA
SPOLETO GUARÁ MM	ROSA ALICE GUEDES DE SOUZA
SPOLETO SHOPPING SUL	ROSA ALICE GUEDES DE SOUZA
SPOLETO DARK KITCHEN ALTANA MM	ROSA ALICE GUEDES DE SOUZA
SPOLETO QUE GAMA MM	ROSA ALICE GUEDES DE SOUZA
SPOLETO SHOPPING BOULEVARD BRASILIA	ROSA ALICE GUEDES DE SOUZA
SPOLETO JARDIM BOTANICO DF	ROSA ALICE GUEDES DE SOUZA
SPOLETO SHOPPING JARDIM NORTE	MAYARA MOREIRA DAMASCO
SPOLETO ARAXÁ	TEREZA CRISTINA
SPOLETO BH SHOPPING	TEREZA CRISTINA
SPOLETO SHOPPING BOULEVARD BH	TEREZA CRISTINA
SPOLETO CENTRO BH	TEREZA CRISTINA
SPOLETO SHOPPING DIAMOND MALL	TEREZA CRISTINA
SPOLETO GUTIERREZ MM --> PRADO	TEREZA CRISTINA
SPOLETO GV SHOPPING	TEREZA CRISTINA
SPOLETO ITAU POWER SHOPPING	TEREZA CRISTINA
SPOLETO METROPOLITAN SHOPPING BETIM	TEREZA CRISTINA
SPOLETO MINAS SHOPPING	TEREZA CRISTINA
SPOLETO PATIO DIVINOPOLIS	TEREZA CRISTINA
SPOLETO RODOVIARIA BH	TEREZA CRISTINA
SPOLETO RUA SAVASSI MM	TEREZA CRISTINA
SPOLETO SHOPPING SETE LAGOAS	TEREZA CRISTINA
SPOLETO SHOPPING CIDADE	TEREZA CRISTINA
SPOLETO SHOPPING CONTAGEM	TEREZA CRISTINA
SPOLETO SHOPPING DEL REY	TEREZA CRISTINA
SPOLETO SHOPPING ESTACAO BH	TEREZA CRISTINA
SPOLETO SHOPPING IPATINGA	TEREZA CRISTINA
SPOLETO SHOPPING MONTES CLAROS	TEREZA CRISTINA
SPOLETO SHOPPING VIA CAFÉ GARDEM	TEREZA CRISTINA
SPOLETO VIA SHOPPING BARREIRO	TEREZA CRISTINA
SPOLETO BETIM MM	TEREZA CRISTINA
SPOLETO PATIO SAVASSI	TEREZA CRISTINA
SPOLETO OUTLET SÓ MARCAS MM	TEREZA CRISTINA
SPOLETO PATIO MATOSINHO PICCOLO	TEREZA CRISTINA
SPOLETO AEROPORTO CONFINS	TEREZA CRISTINA
SPOLETO BOULEVARD COLINA	TEREZA CRISTINA
SPOLETO LAGOA SANTA	TEREZA CRISTINA
SPOLETO LAVRAS	TEREZA CRISTINA
`;

function normalize(str) {
  return str
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]/g, '');
}

const lines = rawData.trim().split('\n').filter(l => l.trim());
const storeMap = new Map();

for (const line of lines) {
  const parts = line.split('\t');
  if (parts.length < 2) continue;
  const storeName = parts[0].trim();
  const consultantName = parts[1].trim();
  storeMap.set(normalize(storeName), consultantName);
}

const unassignedStores = [];
for (const s of INITIAL_STORES) {
  const norm = normalize(s.name);
  if (!storeMap.has(norm)) {
    // try partial
    let matchedCons = null;
    for (const [k, v] of storeMap.entries()) {
      if (k.includes(norm) || norm.includes(k)) {
        matchedCons = v;
        break;
      }
    }
    if (!matchedCons) {
      unassignedStores.push(s);
    }
  }
}

console.log('Lojas sem consultor atribuído:', unassignedStores.length);
unassignedStores.forEach(s => console.log(`- ${s.id} | ${s.code} | ${s.name} (${s.city}/${s.state})`));
